# This is a TOML document. Boom

version = "1.0.0"
user = "nobody"
pid = "/tmp/point.pid"
dir = "./"
perf = "0.0.0.0:6420"

[log]
dir = "/data/log/point"

[bm]
	[bm.inner]
	addr = "0.0.0.0:9002"
	maxListen = 10
	timeout = "1s"
	[bm.local]
	addr = "0.0.0.0:9003"
	maxListen = 10
	timeout = "1s"

[mysql]
	addr = "127.0.0.1:3306"
	dsn = "root:123456@tcp(127.0.0.1:3306)/bilibili_point?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"
	[mysql.breaker]
	window = "3s"
	sleep = "100ms"
	bucket = 10
	ratio = 0.5
	request = 100

[memcache]
	name = "point"
	proto = "tcp"
	addr = ""
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[dataBus]
  [dataBus.OldVipBinlog]
    key = "4ba46ba31f9a44ef"
    secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
    group = "VipBinlog-MainAccount-Point-S"
    topic = "VipBinlog-T"
    action = "sub"
    offset = "old"
    buffer = 1024
    name = "vip-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
  [dataBus.PointBinlog]
    key = "4ba46ba31f9a44ef"
    secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
    group = "PointBinlog-MainAccount-S"
    topic = "PointBinlog-T"
    action = "sub"
    offset = "old"
    buffer = 1024
    name = "vip-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
  [dataBus.PointUpdate]
    key = "4ba46ba31f9a44ef"
    secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
    group = "PointUpdate-MainAccount-S"
    topic = "PointUpdate-T"
    action = "sub"
    offset = "old"
    buffer = 1024
    name = "vip-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[httpClient]
    key = "5245acedbb88a3e2"
    secret = "66998d7f276f47b0fd31dc026c9f22cf"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
    [httpClient.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[properties]
    notifyCacheDelURL = ["http://account.bilibili.co/api/communicate/purge_cache"]