[log]
    stdout = true
    # dir = "./log/bbq"
    v = 5

[grpc]
    timeout = "500ms"
    addr = "0.0.0.0:9003"

[bm]
    addr = "0.0.0.0:8802"
    timeout = "2s"

[mysql]
	addr = "172.16.38.91:3306"
	dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "2000ms"
	execTimeout = "2000ms"
	tranTimeout = "3000ms"

[redis]
	name = "bbq-web"
	proto = "tcp"
	addr = "172.16.38.91:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[gRPCClient]
    [gRPCClient.push]
		addr = "172.16.38.91:9093"
        [gRPCClient.push.wardenconf]
            dial = "100ms"
            timeout = "500ms"

[l1PushStrategy]
	[l1PushStrategy.like]
		t = 1
		a = -1
		b = -1
	[l1PushStrategy.comment]
		t = 1
		a = -1
		b = -1
	[l1PushStrategy.follow]
		t = 1
		a = -1
		b = -1
	[l1PushStrategy.sysmsg]
		t = -1
		a = -1
		b = -1

[l2PushStrategy]
	[l2PushStrategy.like]
		t = 1
		a = -1
		b = 5
	[l2PushStrategy.comment]
		t = 1
		a = -1
		b = 5
	[l2PushStrategy.follow]
		t = 1
		a = -1
		b = 5
	[l2PushStrategy.sysmsg]
		t = 1
		a = -1
		b = -1

[infoc]
    taskID = "001730"
    proto = "tcp"
    addr = "172.18.33.124:15140"
    chanSize = 10240