[log]
	dir = "/data/log/riot-search"
    
[Riot]
    Dict = "/data/static/riot-search/dictionary.txt"
    StopToken = "/data/static/riot-search/stop_tokens.txt"
    NumShards = 4
    Timeout = 800
    FlushTime = 10

[BM]
    addr = "0.0.0.0:7871"
    timeout = "1s"

[HTTPClient]
    key = "test"
    secret = "test"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[Databus]
    key = "2511663d546f1413"
    secret = "cde3b480836cc76df3d635470f991caa"
    group = "ArchiveNotify-MainSearch-S"
    topic = "ArchiveNotify-T"
    action ="sub"
    name = "riot"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "40s"
    writeTimeout = "1s"
    idleTimeout = "60s"

[Mysql]
    addr = "172.22.34.101:3306"
    dsn = "bili_search:BzwF6Ez64RT6Yy2alSKDFGCPgGX5tMlj@tcp(172.22.34.101:3306)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
