# This is a TOML document. Boom.
# This is tag-admin TOML DEMO, you can use it in DEV, Test and UAT env

version = "1.0.0"
user = "nobody"
pid = "/tmp/tag-admin.pid"
dir = "./"
perf = "0.0.0.0:6920"

[log]
    dir = "/data/log/tag-admin/"

[agentLog]
    open = false
    business = 51
    [agent]
    taskID ="000293"
    proto = "unixgram"
    addr = "/var/run/lancer/collector.sock"
    chan = 10240
    buffer = 10240
    timeout = "500ms"

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
        key = "manager-go"
        secret = "949bbb2dd3178252638c2407578bc7ad"
        dial = "1s"
        timeout = "1s"
        keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
    [auth.MaHTTPClient]
        key = "f6433799dbd88751"
        secret = "36f8ddb1806207fe07013ab6a77a3935"
        dial = "1s"
        timeout = "1s"
        keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
    [auth.session]
        sessionIDLength = 32
        cookieLifeTime = 1800
        cookieName = "mng-go"
        domain = ".bilibili.co"
    [auth.session.Memcache]
        name = "go-business/auth"
        proto = "tcp"
        addr = "172.18.33.61:11232"
        active = 5
        idle = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"

[ecode]
   #domain = "172.16.33.248:6401"
    domain = "uat-api.bilibili.co"
    all = "1h"
    diff = "10m"
    [ecode.clientconfig]
        dial      = "2000ms"
        timeout   = "2s"
        keepAlive = "10s"
        timer     = 128
        key = "3c4e41f926e51656"
        secret = "26a2095b60c24154521d24ae62b885bb"
        [ecode.clientconfig.breaker]
            window  ="3s"
            sleep   ="100ms"
            bucket  = 10
            ratio   = 0.5
            request = 100

[HTTPServer]
    addr = "0.0.0.0:6921"
    maxListen = 1000
    timeout = "100ms"
    readTimeout = "100ms"
    writeTimeout = "200ms"

[mysql]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/platform_tag?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 1
    idle = 1
    IdleTimeout = "1s"
    QueryTimeout = "1s"
    ExecTimeout = "1s"
    TranTimeout = "1s"
    [mysql.breaker]
        window  ="1s"
        sleep   ="100ms"
        bucket  = 10
        ratio   = 0.1
        request = 100

[perms]
    auditFirst = "TAG_FIRST"
    auditSecond = "TAG_SECOND"
    relation = "TAG_RELATION"
    hot = "TAG_HOT"
    whiteList = "TAG_ROLE"
    videoLock = "TAG_RELATION"
    synonym = "TAG_SYNONYM"
    log = "TAG_LOG"
    report = "TAG_REPORT"
    edit = "TAG_INFO"
    add = "TAG_INFO"
    del = "TAG_INFO"
    examine = "TAG_INFO"
    limit = "TAG_ROLE"
    channel = "CHANEL_INFO"

[HTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    key = "3c4e41f926e51656"
	secret = "26a2095b60c24154521d24ae62b885bb"
    [httpClient.breaker]
        window  ="10s"
        sleep   ="10ms"
        bucket  = 10
        ratio   = 0.1
        request = 100

[redis]
    [redis.tag]
        name = "tag-service"
        proto = "unix"
        addr = "/tmp/uat-tag-service-redis.sock"
        active = 10
        idle = 5
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"

[memcache]
    [memcache.tag]
        name = "tag-service"
        proto = "unix"
        addr = "/tmp/uat-tag-service-mc.sock"
        idle = 5
        active = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"

[rpcClient2]
    [rpcClient2.account]
        group= "groupapp"
        pullInterval = "10s"
        [rpcClient2.account.client]
        timeout = "1s"
        timer = 1000
        [rpcClient2.account.client.breaker]
            window  ="3s"
            sleep   ="100ms"
            bucket  = 10
            ratio   = 0.5
            request = 100
            [[rpcClient2.account.backup]]
            proto = "tcp"
            addr = "172.16.33.56:6079"
            timeout = "1s"
            timer = 1000
        [rpcClient2.account.zookeeper]
        root = "/microservice/account-service/"
        addrs = ["172.18.33.172:2181"]
        timeout = "30s"

[hosts]
    mngSearchHost = "http://uat-bili-search.bilibili.co"
    blackFilterHost = "http://uat-api.bilibili.com"
    platformHost = "http://uat-api.bilibili.co"
    hotTagHost = "http://data-test.bilibili.co/y3kflg2k"
    hotCastHost = "http://172.18.4.103:30001"
    accountHost = "http://uat-account.bilibili.com"
    messageHost = "http://uat-message.bilibili.com"

[tag]
    hotSyncTime = "1h"
    traversalTime = "5s"
    maxSubmitNum = 50
    tagExpire = "8h"
    resExpire = "8h"
    subExpire = "8h"