# This is a TOML document. Boom.
[host]
api = "http://uat-api.bilibili.com"
mission = "http://172.16.33.104"
account = "http://account.bilibili.co"
manager = "http://manager.bilibili.co"
mngsearch = "http://bili-search.bilibili.co"
task = "http://archive.api.bilibili.co"
archive = "http://archive.api.bilibili.co"
data = "http://data.bilibili.co"

[xlog]
dir = "/data/log/videoup-admin/"
    [xlog.elk]
    project = "videoup-admin"
    addr = "172.18.20.17:8520"
    chanSize = 10240


[statsd]
project = "videoup-admin"
addr = "172.18.20.15:8200"
chanSize = 10240


[app]
key = "c05dd4e1638a8af0"
secret = "7daa7f8c06cd33c5c3067063c746fdcb"

[httpClient]
    [httpClient.read]
     key = "f265dcfa28272742"
     secret = "437facc22dc8698b5544669bcc12348d"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.read.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.write]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.write.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.search]
        key = "6aa4286456d16b97"
        secret = "351cf022e1ae8296109c3c524faafcc8"
        dial = "1s"
        timeout = "3s"
        keepAlive = "60s"
        timer = 1000
        [httpClient.search.breaker]
        window  = "10s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[bm]
	addr = "0.0.0.0:6324"
    maxListen = 1000
    timeout = "1s"

#db for fat   172.16.33.205:3308
#db for uat   172.22.34.101:3306
[ormArchive]
 dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2
idleTimeout = "4h"

[db]
    [db.archive]
    name = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.archive.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.archiveRead]
    name = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.archiveRead.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dede]
    name = "172.16.33.54:3307"
    dsn = "dede_test:dede_test@tcp(172.16.33.54:3307)/bilibili?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.dede.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.manager]
    name = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_manager?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.manager.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.oversea]
    name = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_oversea?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.oversea.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.creative]
    name = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_creative?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.creative.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    csrf = true
    [identify.app]
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 2
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.httpClient]
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "unix"
    addr = "/tmp/uat-manager-auth-mc.sock"
    active = 5
    idle = 2
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[accountRPC]
    timeout = "10s"

[videoupPub]
key = "0PtMsLLxWyyvoTgAyLCD"
secret = "0PtMsLLxWyyvoTgAyLCE"
group = "Videoup-Videoup2Bvc-P"
topic = "Videoup2Bvc"
action = "pub"
name = "videoup-admin/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[upCreditPub]
    key = "4c76cbb7a985ac90"
    secret = "43bb22ce34a6b13e7814f09cb8116522"
    group = "UpCreditLog-MainArchive-P"
    topic = "UpCreditLog-T"
    action = "pub"
    name = "videoup-admin/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout="1s"
    writeTimeout="1s"
    idleTimeout="10s"


[redis]
    [redis.track]
    name = "video-admin/track"
    proto = "tcp"
    addr = "172.18.33.61:6807"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "10s"
    [redis.secondary]
    name = "videoup-admin/secondary"
    proto = "tcp"
    addr = "172.22.33.137:6835"
    active = 10
    idle = 2
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"


    [redis.task]
    name = "video-admin/task"
    proto = "tcp"
    addr = "172.18.33.61:6807"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
    [hbase.zookeeper]
    root = ""
    addrs = ["172.18.33.131:2181","172.18.33.168:2181","172.18.33.169:2181"]
    timeout = "30s"

[tagDisRPC]
    timeout="1s"