# This is a TOML document. Boom.
version = "1.0.0"

[log]
  stdout = true
  dir = "/data/log/up-rating-admin/"

[db]
[db.rating]
  dsn = "gaopeng:V8ktIf7HzvpPSsZeNy5ClWw1RYFAmUDJ@tcp(172.16.33.205:3308)/bilibili_up_rating?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  idle = 5
  idleTimeout = "4h"
  queryTimeout = "5s"
  execTimeout = "5s"
  tranTimeout = "10s"
  [db.level.breaker]
  window = "3s"
  sleep = "100ms"
  bucket = 10
  ratio = 0.5
  request = 100

[rpcclient]
    [rpcclient.account]
		timeout = "1s"

[bm]
  addr = "0.0.0.0:8410"
  maxListen = 10
  timeout = "10s"
