# convey 测试用  注意每次会重置redis/memcache里的数据

[xlog]
    dir = "/data/log/feed-service/"
    [xlog.syslog]
    proto = "udp"
    addr = "172.18.19.22:9999"
    project = "web-interface"
    chanSize = 10240

[bm]
     addr = "0.0.0.0:6362"
     timeout = "1s"

[rpcServer]
    proto = "tcp"
    addr = "127.0.0.1:6361"

[accountRPC]

[archiveRPC]

[articleRPC]

[multiRedis]
maxArcsNum = 50 # 对每个up主回源时候 一次最多拿多少个稿件 也是每个up主稿件缓存的限制量
TTLUpper = "480h"
expireUpper = "480h"
expireFeed = "16h"
[multiRedis.Cache]
    name = "feed-service"
    proto = "tcp"
    addr = "127.0.0.1:6379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[memcache]
    name = "feed-service"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    idle = 10
    active = 10
    dialTimeout = "2s"
    readTimeout = "2s"
    writeTimeout = "2s"
    idleTimeout = "7h"
    expire = "15m"
    bangumiExpire = "15m"

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer = 10
[httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[feed]
  appLength = 200
  webLength = 400
  archiveFeedLength = 200
  archiveFeedExpire = "5m"
  bangumiFeedExpire = "5m"
  appPullInterval = "5m"
  webPullInterval = "15s"
  bulkSize = 500
  minUpCnt    = 10
  maxTotalCnt = 100
