version = "1.0.0"
user    = "nobody"
pid     = "/tmp/click-job.pid"
dir     = "./"
perf    = "127.0.0.1:6440"
trace   = false
debug   = false
env     = "uat"

chanNum = 50
hashNum = 500000
consumeNum = 10
needInit = false
lastChangeTime = 75
releaseTime = 600

[cacheConf]
ArcUpCacheTime = 600
PGCReplayTime = 1800
newAnonymousCacheTime = 60
NewAnonymousBvCacheTime = 300

[xlog]
dir = "/data/log/click-job/"

[infoc2]
taskID = "000025"
proto = "tcp"
addr = "172.16.113.149:15140"
chanSize = 10240

[multiHTTP]
    [multiHTTP.inner]
    addrs = ["0.0.0.0:6441"]
    [multiHTTP.local]
    addrs = ["0.0.0.0:6442"]

[db]
addr = "172.22.34.101:3306"
dsn = "test:test@tcp(172.16.33.205:3308)/archive_click?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
active = 100
idle = 50
idleTimeout ="4h"
queryTimeout = "300ms"
execTimeout = "300ms"
tranTimeout = "500ms"
[db.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
name = "click-job/redis"
proto = "unix"
addr = "/tmp/uat-archive-service-redis.sock"
active = 10
idle = 1
dialTimeout = "1s"
readTimeout = "2s"
writeTimeout = "2s"
idleTimeout = "80s"

[statPub]
key = "0QNB0ZgFozbKUCQhbTq8"
secret = "0QNB0ZgFozbKUCQhbTq9"
group = "Stat-UGC-P"
topic = "Stat-T"
action = "pub"
name = "stat-pub/stat-pub"
proto = "tcp"
addr = "172.18.33.50:6205"
active = 5
idle = 1
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"

[StatViewPub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatView-MainAppSvr-P"
topic = "StatView-T"
action = "pub"
name = "stat-pub/stat-pub"
proto = "tcp"
addr = "172.18.33.50:6205"
active = 5
idle = 1
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"

[ReportDatabus]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "ArchiveClick-MainArchive-S"
topic = "ArchiveClick-T"
action = "sub"
name = "report-click/sub"
proto = "tcp"
addr = "172.18.33.50:6205"
active = 5
idle = 1
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"


[HTTPClient]
key       = "e7482d29be4a95b8"
secret    = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "200ms"
keepAlive = "60s"
    [HTTPClient.breaker]
    window  = "1s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[archiveRPC]
    group = "uat"
    pullInterval = "10s"
    [archiveRPC.client]
    token = "lY0h6KmXH7u9ftRIuhQTkOYqUg10gwHG"
    timeout = "1s"
    [archiveRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10        
    ratio   = 0.5
    request = 100
    [archiveRPC.zookeeper]
    root = "/microservice/archive-service/"
    addrs = ["172.18.33.50:2199","172.18.33.51:2199","172.18.33.52:2199"]
    timeout = "30s"