# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/player.pid"
dir = "./"
perf = "127.0.0.1:6260"
checkFile = "/data/www/player-interface.html"
family = "player-interface"
address = "172.16.33.56"

env = "test"
tick = "5m"

[Broadcast]
tcpAddr = "172.16.0.238:4080"
wsAddr = "172.16.0.238:4090"
wssAddr = "chat2.bilibili.com:4095"
begin = "2016-10-31 00:00:00"
end = "2017-01-20 23:59:59"

[policy]
id=1
des="D区广告方案新版灰度"
type="用户随机-尾号"
start="2016-12-06 00:00:00"
end="2017-12-01 00:00:00"
mtime="2016-12-07 15:09:00"

[[pitem]]
Id=1
Data="new"
Comment="新样式"
ExtData="00-04"

[[pitem]]
Id=2
Data="old"
Comment="旧样式"
ExtData="05-99"

[[pitem]]
Id=3
Data="old"
Comment="默认/未登录"
ExtData="default"

[matsuri]
pastID = 5461206
matID = 5461533
matTime = "2016-12-15T16:57:03+08:00"
tick = "10s"

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "6a29f8ed87407c11"
    secret = "d3c5a85f5b895a03735b5d20a273bc57"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[player]
IPFile = "/data/conf/iprepo/iprepo.txt"

[host]
apiCo = "http://api.bilibili.co"

[xlog]
    dir = "/data/log/player-interface/"

[ecode]
service = "player-interface"
    [ecode.mysql]
    name = "[player-interface]tcp@172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_apm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5

[tracer]
proto = "tcp"
addr = "172.16.33.46:5140"
tag = "platform/player-inferface"


[app]
key = "3c4e41f926e51656"
secret = "26a2095b60c24154521d24ae62b885bb"

[httpClient]
	dial = "500ms"
	timeout = "500ms"
	keepAlive = "60s"
	timer = 1000

[multiHttp]
    [multiHttp.outer]
    addrs = ["0.0.0.0:6261"]
    maxListen = 1000
    [multiHttp.inner]
    addrs = ["0.0.0.0:6262"]
    maxListen = 1000
    [multiHttp.local]
    addrs = ["0.0.0.0:6263"]
    maxListen = 1000

[mysql]
    [mysql.player]
    addr = "172.16.33.54"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_player?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    [mysql.dede]
    addr = "172.16.0.5"
    dsn = "bilibili:5Fq2M4FbPZK4fhtE@tcp(172.16.0.5:3306)/bilibili?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2

[accountRPC]
    pullInterval = "10s"
    [accountRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6079"
    timeout = "1s"
    timer = 1000
    [[accountRPC.backup]]
    proto = "tcp"
    addr = "172.16.33.56:6079"
    timeout = "1s"
    timer = 1000
    [accountRPC.zookeeper]
    root = "/microservice/account-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[archiveRPC]
    pullInterval = "10s"
    [archiveRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6089"
    timeout = "1s"
    timer = 1000
    [[archiveRPC.backup]]
    proto = "tcp"
    addr = "172.16.33.56:6089"
    timeout = "1s"
    timer = 1000
    [archiveRPC.zookeeper]
    root = "/microservice/archive-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"
