[log]
    stdout = true
    # dir = "./log/bbq"
    v = 15

[grpc]
    timeout = "500ms"
    addr = "0.0.0.0:9004"

[bm]
    addr = "0.0.0.0:8802"
    timeout = "2s"

[mysql]
	addr = "172.16.38.91:3306"
	dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "800ms"
	execTimeout = "800ms"
	tranTimeout = "1000ms"

[redis]
	name = "bbq-web"
	proto = "tcp"
	addr = "172.16.38.91:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[grpcClient]
    [grpcClient.account]
		addr = "discovery://default/account.service"
        [grpcClient.account.wardenconf]
            dial = "100ms"
            timeout = "500ms"
    [grpcClient.notice]
        addr = "discovery://default/bbq.service.notice"
        [grpcClient.notice.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.filter]
		addr = "discovery://default/filter.service"
        [grpcClient.filter.wardenconf]
            dial = "100ms"
            timeout = "500ms"

[databus]
	[databus.bfs]
       	key = "36ff3e402f7c310a"
        secret = "dbd11b140486dc0bc263cf7ec540186c"
        group = "Bfs-Yellow-Res-BbqBbq-S"
        topic = "Bfs-Yellow-Res-T"
        action = "sub"
        buffer = 1024
        name = "history"
        proto = "tcp"
        addr = "172.22.33.174:6205"
        idle = 1
        active = 1
        dialTimeout = "1s"
        readTimeout = "60s"
        writeTimeout = "1s"
        idleTimeout = "10s"
		[databus.bfs.discovery]
			domain = "api.bilibili.co"
			key = "c8c48e784e05acfb"
			secret = "aa63ee0a10afa358d02a07e7abcec546"
			region = "sh"
			zone = "sh001"
			env = "uat"