version = "1.0.0"
user    = "nobody"
pid     = "/tmp/activity-job.pid"
dir     = "./"
perf    = "0.0.0.0:7750"
trace   = false
debug   = false
env     = "test"

[interval]
coinInterval = "30ms"
queryInterval = "100ms"
objStatInterval = "5m"
viewRankInterval = "5m"
kingStoryInterval = "5m"

[log]
    dir = "/data/log/activity-job/"

[app]
key = "BjeiOXmiL363sAt8"
secret = "0J18o2qCeuWzo6ScBpm4QZJO8Ij5kcvz"

[HTTPServer]
    addrs = ["0.0.0.0:7751"]
    readTimeout = "1s"
    writeTimeout = "1s"
    maxListen = 10

[HttpClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "500ms"
    timeout = "2s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.1
    request = 10

[mysql]
    [mysql.like]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.like.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[memcache]
accessExpire = "10s"
likeExpire = "3s"
    [memcache.like]
    name = "activity/test"
    proto = "tcp"
    addr = "172.18.33.61:11220"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[redis]
name = "activity-job"
proto = "tcp"
addr = "172.16.33.104:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "10s"

[host]
apiCo = "http://api.bilibili.co"
activity = "http://uat-www.bilibili.com"

[rule]
broadcastSid = 0

[actSub]
    key = "9765cdac5894f2ba"
    secret = "f4237d712c3ed1e7fab0137b81418b14"
    group = "Lottery-MainWebSvr-S"
    topic = "Lottery-T"
    action = "sub"

[bnjSub]
    key = "9765cdac5894f2ba"
    secret = "f4237d712c3ed1e7fab0137b81418b14"
    group = "ActBnjPreview-MainWebSvr-S"
    topic = "ActBnjPreview-T"
    action = "sub"

[bnj2019]
    lid = 1
    startTime = "2018-12-11T15:04:05+08:00"
    timelinePic = ""
    msgSpec = "1 42,43 15 * * *"
    midLimit = 1000
    wxTitle = "【拜年祭必看！】拜年祭预约人数到达预警"
    wxUser = "zhangshuyi,huangyukun,xuwenqi01,wuhao02,liweijia"
    [[bnj2019.time]]
        second = 60
        score = 95
        step = 4
        wxMsg = ""
        msg = "拜年祭预约人数即将到达200w，请及时准备拜年祭抽奖事项。"
    [[bnj2019.time]]
        second = 120
        score = 90
        step = 3
        wxMsg = ""
        msg = "拜年祭预约人数即将到达150w，请及时准备拜年祭抽奖事项。"
    [[bnj2019.message]]
        start = "2018-12-24T15:40:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】001"
        content = "飞雪连天射白鹿，笑书神侠倚碧鸳。当V家碰到金庸，会碰撞出怎样的火花？来拜年祭后台看看吧~"
        mc = "1_21_1"
    [[bnj2019.message]]
        start = "2018-12-24T15:43:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】002"
        content = "前有某任乱斗，今有b站混战。小电视：妈妈，快看神仙打架！链接"
        mc = "1_21_2"
    [[bnj2019.message]]
        start = "2019-01-31T00:00:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】003"
        content = "站内最强甜美系女歌手，真情翻唱哥哥凄美情歌。请跟随小电视到她的休息室看看吧~链接"
        mc = "1_21_3"
    [[bnj2019.message]]
        start = "2019-02-01T00:00:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】004"
        content = "什么？我喜欢的动画小哥哥和小姐姐们要来上海一日游？！快来和小电视一起研究哪些地方偶遇他们吧！链接"
        mc = "1_21_4"
    [[bnj2019.message]]
        start = "2019-02-02T00:00:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】005"
        content = "妹子眼里的钢铁直男？不，是冷冷的狗粮在脸上胡乱地拍。来，今日份的狗粮。链接"
        mc = "1_21_5"
    [[bnj2019.message]]
        start = "2019-02-03T00:00:00+08:00"
        title = "【bilibili2019拜年祭档案揭秘】006"
        content = "真相只有一个喵！点击开始解谜。链接"
        mc = "1_21_6"



[vipSub]
key = "9765cdac5894f2ba"
secret = "f4237d712c3ed1e7fab0137b81418b14"
group = "VipBinlog-MainWebSvr-S"
topic = "VipBinlog-T"
action = "sub"

[kfcSub]
key = "9765cdac5894f2ba"
secret = "f4237d712c3ed1e7fab0137b81418b14"
group = "KfcCouponAward-MainWebSvr-S"
topic = "KfcCouponAward-T"
action = "sub"
