[bm]
	addr = "0.0.0.0:6812"
    maxListen = 1000
    timeout = "1s"

[httpClient]
key = "3c4e41f926e51656"
secret ="26a2095b60c24154521d24ae62b885bb"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer = 10
[httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[databus]
key = "0QNB0ZgFozbKUCQhbTq8"
secret = "0QNB0ZgFozbKUCQhbTq9"
group = "PassportBinlog-Login-S"
topic = "Passport-T"
action = "sub"
offset = "new"
buffer = 2048
name = "secure-service/databus"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[mysql]
[mysql.secure]
addr = "172.22.34.101:3309"
dsn = "secure:cvETlGWr360LVzQPeJwydStxmA78Z4hX@tcp(172.22.34.101:3309)/bilibili_secure?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 3
idle = 1
idleTimeout ="4h"
queryTimeout = "100ms"
execTimeout = "100ms"
tranTimeout = "200ms"
[mysql.secure.breaker]
window = "3s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100

[mysql.ddl]
addr = "172.22.34.101:3309"
dsn = "secure_ddl:c1GoSPd8O2KgBvkeRTbWMufNyzHiw6aV@tcp(172.22.34.101:3309)/bilibili_secure?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 3
idle = 1
idleTimeout ="4h"
queryTimeout = "100ms"
execTimeout = "100ms"
tranTimeout = "200ms"
[mysql.ddl.breaker]
window = "3s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100

[rpcServer]
    proto = "tcp"
    addr = "0.0.0.0:6819"
    weight = 10

[locationrpc]
    timeout = "30s"

[redis]
    name = "secure-service/secure"
    proto = "tcp"
    addr = "172.18.33.61:6839"
    idle = 2
    active = 20
    dialTimeout = "100ms"
    readTimeout = "350ms"
    writeTimeout = "350ms"
    idleTimeout = "80s"
    expire = "1h"
    doubleCheck="720h"

[memcache]
name = "secure-service"
proto = "tcp"
addr = "172.18.33.61:11212"
idle = 1
active = 10
dialTimeout = "100ms"
readTimeout = "200ms"
writeTimeout = "200ms"
idleTimeout = "80s"
expire = "9h"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
    [hbase.zookeeper]
    root = ""
     addrs = ["172.18.33.75:2181" ]
    timeout = "30s"
[Expect]
Top = 3
Count =2
closeCount = 1000
Rand = 1