# This is a TOML config file.

[infoc2]
taskID = "000279"
proto = "tcp"
addr = "172.18.33.125:15140"
chanSize = 10240

[infocBak]
taskID = "000279"
proto = "tcp"
addr = "172.18.33.125:15140"
chanSize = 10240

[httpServer]
    addr = "0.0.0.0:6311"
    maxListen = 100
    timeout = "10s"

[db]
    [db.dm]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_dm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dm.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmMetaWriter]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmMetaWriter.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmMetaReader]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmMetaReader.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[memcache]
    [memcache.filter]
    name = "filter"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [memcache.subtitle]
    name = "dm2"
    proto = "tcp"
    addr = "172.16.33.54:11211"
     idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"


[host]
    api = "http://api.bilibili.co"
    videoup = "http://archive.api.bilibili.co"
    search = "http://uat-manager.bilibili.co"
    season = "http://uat-manager.bilibili.co"
    message = "http://message.bilibili.co"
    account = "http://account.bilibili.co"
    mask = "http://172.22.33.111:8200"
    berserker = "http://berserker.bilibili.co/avenger/api/148/query"

[httpClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "2s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpSearch]
    key = "89ffc6e896106fd3"
    secret = "1359cdbaf9ff6e2f9b6251579d966101"
    dial = "1s"
    timeout = "8s"
    keepAlive = "60s"
    timer = 1000
    [httpSearch.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpInfoc]
    infocQueryURL = "http://172.18.33.160:6010/avenger/api/2/query"
    key = "f43ae8af9179884d0f7e3d6e532dd1bd"
    secret = "3e4078b4e9448ef12528b68a22c1fa60"
    dial = "1s"
    timeout = "2s"
    keepAlive = "60s"
    timer = 1000
    [httpInfoc.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    
[accountRPC]
    timeout = "2s"


[archiveRPC]
    timeout = "1s"

[actionpub]
    key = "0Pub71WwEMKXu63qtztu"
    secret= "0Pub71WwEMKXu63qtztv"
    group= "DMAction-UGC-P"
    topic= "DMAction-T"
    action="pub"
    name = "dm-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 5
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[managerAuth]
managerHost = "http://uat-manager.bilibili.co"
dashboardHost = "http://dashboard-mng.bilibili.co"
dashboardCaller =  "manager-go"
    [managerAuth.dsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [managerAuth.dsHTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [managerAuth.maHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [managerAuth.maHTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [managerAuth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [managerAuth.session.Memcache]
    name = "dmadmin-auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[elastic]
host = "http://uat-manager.bilibili.co"
[elastic.HTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [elastic.HTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    
[managerLog]
    Key     =   "2511663d546f1413"
    Secret  =   "cde3b480836cc76df3d635470f991caa"
    Group   =   "LogAudit-MainSearch-P"
    Topic   =   "LogAudit-T"
    Action  =   "pub"
    Buffer  =   10240
    Name    =   "log-audit/log-sub"
    Proto   =   "tcp"
    Addr    =   "172.18.33.50:6205"
    Active  =   10
    Idle    =   5
    DialTimeout     =  "200ms"
    ReadTimeout     =  "200ms"
    WriteTimeout    = "200ms"
    IdleTimeout     =  "80s"
