[archive]
    state = 0
    notAccess = 10000
    tid = [11, 13, 23, 165, 177, 4, 5]
    subTid = [130, 54, 71, 174, 153, 169, 170]
    title = ["搬运", "抖音", "快手", "秒拍", "美拍", "微视", "西瓜视频", "火山视频", "火山小视频", "纳豆视频", "电流小视频"]
    content = ["搬运", "抖音", "快手", "秒拍", "美拍", "微视", "西瓜视频", "火山视频", "火山小视频", "纳豆视频", "电流小视频", "转侵删", "来自网络", "韩国车展", "韩国车模", "付邮送", "退坑出", "出簪", "抽福袋", "评论抽"]

[up]
    uname = ["搬运", "抖音", "快手"]
    mid = [330061605, 38331436, 348608259, 39735082]

[dimension]
    minX = 720
    minYX = 1.75
    maxYX = 1.80
    maxDuration = 60
    minDuration = 15
