version = "1.0.0"
user = "nobody"
pid = "/tmp/article.pid"
dir = "./"
perf = "0.0.0.0:6750"
family = "article"

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    csrfOn = true
    [identify.app]
    key = "9cfc54570033cd61"
    secret = "9d63835fa38fe58a62d9f49ef5da296f"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.co"
    secret = "http://open.bilibili.co"
  [identify.httpClient]
    key = "9cfc54570033cd61"
    secret = "9d63835fa38fe58a62d9f49ef5da296f"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[rpcServer2]
    token= "123456"
    [[rpcServer2.servers]]
    proto = "tcp"
    addr = "0.0.0.0:6755"
    weight = 10
    [rpcServer2.zookeeper]
    root = "/microservice/article-service-x/"
    addrs =  ["172.16.33.172:2181"]
    timeout = "60s"

[displayInfoc]
taskID = "1"
proto = "tcp"
addr = "127.0.0.1:80"
chanSize = 10240

[clickInfoc]
taskID = "1"
proto = "tcp"
addr = "127.0.0.1:80"
chanSize = 10240

[AIclickInfoc]
taskID = "1"
proto = "tcp"
addr = "127.0.0.1:80"
chanSize = 10240

[ShowInfoc]
taskID = "1"
proto = "tcp"
addr = "127.0.0.1:80"
chanSize = 10240

[CheatInfoc]
taskID = "1"
proto = "tcp"
addr = "127.0.0.1:80"
chanSize = 10240

[log]
    dir = "/data/log/article/"
#[log.syslog]
#    proto = "udp"
#    addr = "172.18.19.22:9999"
#    project = "article"
#    chanSize = 10240

[app]
    key = "9cfc54570033cd61"
    secret = "9d63835fa38fe58a62d9f49ef5da296f"

[bm]
     addr = "0.0.0.0:6751"
     timeout = "1s"

[HTTPClient]
    key = "9cfc54570033cd61"
    secret = "9d63835fa38fe58a62d9f49ef5da296f"
    dial      = "50ms"
    timeout   = "1s"
    keepAlive = "60s"
    timer     = 128
    [HTTPClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[messageHTTPClient]
    key = "9cfc54570033cd61"
    secret = "9d63835fa38fe58a62d9f49ef5da296f"
    dial      = "50ms"
    timeout   = "1s"
    keepAlive = "60s"
    timer     = 128
  [messageHTTPClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
[tracer]
    family = "platform/article"
    proto = "unixgram"
    addr = "/var/run/dapper-collect/dapper-collect.sock"
 
[accountRPC]
    pullInterval = "10s"
    [accountRPC.client]
    timeout = "1500ms"
    [accountRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [accountRPC.conf]
    domain = "api.bilibili.co"
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"

[tagRPC]
    pullInterval = "10s"
    [tagRPC.client]
    proto = "tcp"
    timeout = "1s"
    timer = 1000
    [tagRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [tagRPC.zookeeper]
    root = "/microservice/tag-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[favRPC]
    pullInterval = "10s"
    [favRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6019"
    timeout = "1s"
    timer = 1000
    [favRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [favRPC.zookeeper]
    root = "/microservice/favorite/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[arcRPC]
    pullInterval = "10s"
    group = "test"
    [arcRPC.client]
    proto = "tcp"
    token = "123456"
    timeout = "1s"
    timer = 1000
    [arcRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [arcRPC.zookeeper]
    root = "/microservice/archive-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"
[coinRPC]
    pullInterval = "10s"
    [coinRPC.client]
    proto = "tcp"
    timeout = "1s"
    timer = 1000
    [coinRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [coinRPC.zookeeper]
    root = "/microservice/coin-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[ResRPC]
    pullInterval = "10s"
    [ResRPC.client]
    proto = "tcp"
    timeout = "1s"
    timer = 1000
    [resRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [resRPC.zookeeper]
    root = "/microservice/resource-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"
[ThumbupRPC]
    pullInterval = "10s"
    [ThumbupRPC.client]
    proto = "tcp"
    timeout = "1s"
    timer = 1000
    [ThumbupRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [ThumbupRPC.zookeeper]
    root = "/microservice/thumbup-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[FilterRPC]
    pullInterval = "10s"
    [FilterRPC.client]
    proto = "tcp"
    timeout = "10s"
    timer = 1000
    [FilterRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [FilterRPC.zookeeper]
    root = "/microservice/filter-service/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[HistoryRPC]
    pullInterval = "10s"
    [HistoryRPC.client]
    proto = "tcp"
    timeout = "10s"
    timer = 1000
    [HistoryRPC.client.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [HistoryRPC.zookeeper]
    root = "/microservice/history/"
    addrs = ["172.16.33.172:2181"]
    timeout = "30s"

[redis]
    name = "article"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"



[mysql]
  [mysql.article]
    addr = "172.16.33.54"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_article?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
  [mysql.article.breaker]
  window = "3s"
  sleep = "100ms"
  bucket = 10
  ratio = 0.5
  request = 100
[memcache]
    name = "article"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    idle = 10
    active = 10
    dialTimeout = "2s"
    readTimeout = "2s"
    writeTimeout = "2s"
    idleTimeout = "7h"
    expire = "15m"
	articleExpire  = "10m"
	articleNoFilterExpire  = "5m"
    statsExpire = "15m"
    likeExpire = "72h"
    cardsExpire = "6h"
    submitExpire = "2m"
	ListArtsExpire = "24h"
	ListExpire     = "24h"
	ArtListExpire  = "24h"
    UpListsExpire = "6h"
    ListReadExpire = "1h"
    HotspotExpire = "30m"
    AuthorExpire = "24h"

[ecode]
    domain = "172.16.33.248:6401"
    all = "1h"
    diff = "5m"
    [ecode.clientconfig]
        key = "test"
        secret = "e6c4c252dc7e3d8a90805eecd7c73396"
        dial      = "2000ms"
        timeout   = "2s"
        keepAlive = "10s"
        timer     = 128
        [ecode.clientconfig.breaker]
            window  ="3s"
            sleep   ="100ms"
            bucket  = 10
            ratio   = 0.5
            request = 100
    [ecode.app]
        key = "test"
        secret = "e6c4c252dc7e3d8a90805eecd7c73396"

[statDatabus]
    key = "0QEO9F8JuuIxZzNDvklH"
    secret= "0QEO9F8JuuIxZzNDvklI"
    group= "ArticleStat-Article-P"
    topic= "ArticleStat-T"
    action="pub"
    name = "article/article-pub"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[[RankCategories]]
  name = "月榜"
  id = 1
[[RankCategories]]
  name = "周榜"
  id = 2
[[RankCategories]]
  name = "昨天"
  id = 3
[[RankCategories]]
  name = "前天"
  id = 4
[message]
    URL = "http://message.bilibili.com/api/notify/send.user.notify.do"
    MC = "1_12_1"
[cards]
  TicketURL = "http://api.bilibili.co/api/ticket/project/getcard"
  MallURL = "http://mall.bilibili.co/mall-items/items/itemsListByQuery"
  AudioURL = "http://api.bilibili.co/x/internal/v1/audio/songs/batch"
  BangumiURL = "http://bangumi.bilibili.co/ext/internal/cardinfos"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "150ms"
readsTimeout = "600ms"
writeTimeout = "200ms"
writesTimeout = "600ms"
[hbase.zookeeper]
root = ""
addrs = ["172.18.33.163:2181","172.18.33.164:2181","172.18.33.165:2181"]
timeout = "30s"

[bfs]
timeout="5s"
maxFileSize=5242880
bucket="article"
url="http://bfs.bilibili.co/bfs/article/"
method="PUT"
key="4d08035f0b341509"
secret="ed4161d96c7612b670f75fa4be4e15"

[antispam]
	on=true
  	second=3
   	n=100
   	hour=12
   	m=1000
[antispam.redis]
    name = "article"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
[degradeConfig]
    expire = 86400
    [degradeConfig.memcache]
    name = "article"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    idle = 10
    active = 10
    dialTimeout = "2s"
    readTimeout = "2s"
    writeTimeout = "2s"
    idleTimeout = "7h"

[article]
    expireUpper = "72h"
    expireArtLikes = "72h"
    expireSortArts = "24h"
    TTLSortArts = "72h"
    ExpireRank = "10m"
    TTLRank = "24m"
    ExpireMaxLike = "720h"
    ExpireHotspot = "6h"
    creationDefaultSize = 20
    creationMaxSize = 200
    upperDraftLimit = 30
    upperArticleLimit = 5
    updateRecommendsInteval = "5m"
    maxRecommendPsSize = 100
    maxRecommendPnSize = 10000
    maxUpperListPsSize = 100
    maxArchives = 40
    maxComplaintReasonLimit = 1000
    maxArticleMetas = 100
    maxApplyContentLimit = 5000
    maxApplyCategoryLimit = 200
    maxLikeMidLen = 10
    RecommendAidLen = 20
    SortLimitTime = "504h"
    UpdateBannersInteval = "5m"
    bannerIDs = [2127,2128,2129,2130,2131,2132,2133,2134]
    ActBannerIDs = [2442]
    RecommendRegionLen = 2
    SkyHorseRecommendRegionLen = 5
    RankHost = "http://172.16.33.57:10800"
    MessageMids = []
    MaxContentSize = 1048576
    MaxContentLength = 20000
    MinContentLength = 200
	ActAddURI = "http://matsuri.bilibili.co/api/likes/item/add/%d"
	ActDelURI = "http://matsuri.bilibili.co/api/likes/item/up"
	ActURI = "http://matsuri.bilibili.co/activity/list/article"
    ListLimit = 10
	ListArtsLimit = 500
    AppCategoryName = "更多"
    AppCategoryURL = "http://i0.hdslb.com/bfs/archive/2740eba8124516ac62edf84f65a858ed68b390de.png"
    SkyHorseURL = ""
    SkyHorseGray = [1]
    SkyHorseGrayUsers = [1]
    ListDefaultImage = "http://i0.hdslb.com/bfs/archive/2740eba8124516ac62edf84f65a858ed68b390de.png"
    ExpireReadPing = "2m"
    ExpireReadSet = "24h"