[httpClient]
    key = "654af11b5df0c9d3"
    secret = "a7512b8b243b82f4bdb72cf2824b3f8e"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"


[mysql]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_apm_v2?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    idleTimeout = "7h"
    [mysql.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[tree]
    host = "http://easyst.bilibili.co"
    platformID = "bilibili"
