
[bm]
	addr = "0.0.0.0:7582"
	maxListen = 10
	timeout = "1s"

[mysql]
	addr = "127.0.0.1:3306"
	dsn = "root:123456@tcp(127.0.0.1:3306)/bilibili_point?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"
	[mysql.breaker]
	window = "3s"
	sleep = "100ms"
	bucket = 10
	ratio = 0.5
	request = 100

[memcache]
	name = "point"
	proto = "tcp"
	addr = "172.18.33.61:11241"
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[property]
	pointActiveStartDate = "2018-03-21 17:55:00"
	pointActiveEndDate = "2019-01-21 20:04:05"
        configLoadTick = "60s"
	activityAllowAppID = [3]
	pointGetRule = {"2" = 0,"3" = 50}
        pointWhiteAppkeys = "ad4bb9b8f5d9d4a7"

[rpcServer]
    proto = "tcp"
    addr = "0.0.0.0:7589"
    weight = 10
    group=""

