[incSync]
    switch = false

[fullSync]
    asoCountryCodeSwitch = false
    [fullSync.asoAccount]
        switch = false
        chanNum = 20
        chanSize = 1024
        start = 0
        end = 100000000
        count = 10000
    [fullSync.asoAccountInfo]
        switch = false
        chanNum = 20
        chanSize = 1024
        start = 0
        end = 100000000
        count = 10000
    [fullSync.asoAccountReg]
        switch = false
        chanNum = 20
        chanSize = 1024
        start = 0
        end = 100000000
        count = 10000
    [fullSync.asoAccountSns]
        switch = false
        chanNum = 20
        chanSize = 1024
        start = 0
        end = 100000000
        count = 10000
    [fullSync.asoTelBindLog]
        switch = false
        chanNum = 20
        chanSize = 1024
        start = 0
        end = 100000000
        count = 10000

[scheduler]
    switch = false
    telDuplicateCron = "*/5 * * * * ?"
    emailDuplicateCron = "*/5 * * * * ?"

[bm]
    addr = "0.0.0.0:8000"
    timeout = "1s"

[db]
    [db.originDB]
        addr = "172.22.34.101:3309"
        dsn = "aso:WsjbodupJcZlBeWPEiYyK8HOTIcp3n3Z@tcp(172.22.34.101:3309)/aso?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle = 2
        queryTimeout = "1s"
        execTimeout = "2s"
        tranTimeout = "2s"
        [db.originDB.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
    [db.userDB]
        addr = "172.22.34.101:3308"
        dsn = "passport:G5ntsSqTixJak0oyjceP1buXfVFBQH47@tcp(172.22.34.101:3308)/passport_user?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle = 2
        queryTimeout = "1s"
        execTimeout = "2s"
        tranTimeout = "2s"
        [db.userDB.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
    [db.encryptDB]
        addr = "172.22.34.101:3308"
        dsn = "secret_reader:VK7UMbq8Z4dBxyCzOYkh20EFsa1IWrAi@tcp(172.22.34.101:3308)/passport_secret?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle = 2
        queryTimeout = "1s"
        execTimeout = "2s"
        tranTimeout = "2s"
        [db.encryptDB.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100


[databusUtil]
    size = 200
    num = 32
    ticker = "1s"
    chan = 1024

[databus]
    [databus.asoBinLogSub]
    key = "4ba46ba31f9a44ef"
    secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
    group = "PassportUserBinlog-MainAccount-S"
    topic = "PassportUserBinlog-T"
    action = "sub"
    offset = "old"
    buffer = 2048
    name = "passport-user/databus"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
