# dev config.

[bm]
	addr = "0.0.0.0:7861"
    timeout = "1s"

[rank]
    switchAll = false
    switchIncr = false
    ticker = "10s"
	rowsLimit = 1000
	batchSleep = "10ms"
	batchStep = "24h"
	filePath = "/data/backup/rank-service/"
	fileName = "rmap_%d.pb"


[log]
	dir="/data/log/rank-service"

[mysql]
	[mysql.bilibiliArchive]
	addr = "172.16.33.205:3308"
	dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_archive?timeout=500ms&readTimeout=500ms&writeTimeout=500ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "500ms"
	execTimeout = "500ms"
	tranTimeout = "500ms"
	[mysql.archiveStat]
	addr = "172.16.33.205:3308"
	dsn = "test:test@tcp(172.16.33.205:3308)/archive_stat?timeout=500ms&readTimeout=500ms&writeTimeout=500ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "500ms"
	execTimeout = "500ms"
	tranTimeout = "500ms"
	[mysql.bilibiliTV]
	addr = "172.16.33.205:3308"
	dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_tv?timeout=500ms&readTimeout=500ms&writeTimeout=500ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "500ms"
	execTimeout = "500ms"
	tranTimeout = "500ms"

[databus]
	[databus.StatView]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "Favorite-MainSearch-S"
    topic = "StatView-T"
    action = "sub"
    name = "rank-service/statView-sub"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
	[databus.UgcTvBinlog]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "Favorite-MainSearch-S"
    topic = "UgcTvBinlog-T"
    action = "sub"
    name = "rank-service/UgcTvBinlog-sub"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
	[databus.Archive]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "Rank-MainSearch-S"
    topic = "Archive-T"
    action = "sub"
    name = "rank-service/archive-sub"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

