# This is a TOML document. Boom.

version = "3.0.5"
user = "nobody"
pid = "/tmp/dm-job.pid"
dir = "./"
perf = "0.0.0.0:6215"
checkFile = "/data/www/dm-job.html"

[xlog]
    dir = "/data/log/dm-job/"

[tracer]
    proto = "udp"
    addr = "172.16.33.46:5140"
    family = "dm-job"

[httpServer]
    addr = "0.0.0.0:6216"
    maxListen = 100
    timeout = "1s"

[db]
    [db.dmReader]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "3s"
    execTimeout = "3s"
    tranTimeout = "3s"
    [db.dmReader.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmWriter]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "3s"
    execTimeout = "3s"
    tranTimeout = "3s"
    [db.dmWriter.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    name = "dm-job"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"

[memcache]
    name = "dm-job"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    expire = "24h"

[databus]
    [databus.jobSub]
    key = "0Pub71KvEMKXu63qtztq"
    secret = "0Pub71KvEMKXu63qtztr"
    group = "DMJob-UGC-S"
    topic = "DMJob-T"
    action = "sub"
    name = "dm-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "40s"
    writeTimeout = "1s"
    idleTimeout = "60s"
    [databus.dmMetaCsmr]
    key = "0Pub71KvEMKXu63qtztq"
    secret = "0Pub71KvEMKXu63qtztr"
    group = "DMMeta-DMQueue-S"
    topic = "DMMeta-T"
    action = "sub"
    name = "dm-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "40s"
    writeTimeout = "1s"
    idleTimeout = "60s"

[archiveRPC]
    timeout = "150ms"

[realname]
    switchOn = false
    whitelist = [10109417,1221]
    [realname.threshold]
    "1,2" = 1010

[job]
    flushExpire = "10s"

[bfs]
    host = "http://uat-bfs.bilibili.co"
    timeout = "5s"
    bucket = "test"
    key = "221bce6492eba70f"
    secret = "6eb80603e85842542f9736eb13b7e3"
