
[mysql]
	addr = "127.0.0.1:3306"
	dsn = "test:test@tcp(127.0.0.1:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["test:test@tcp(127.0.0.2:3306)/test? timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4","test:test@tcp(127.0.0.3:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"

[redis]
	name = "app-room-interface"
	proto = "tcp"
	addr = ""
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[memcache]
	name = "app-room-interface"
	proto = "tcp"
	addr = ""
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[log]
	stdout = true


[DMsend]
taskID = "582"
proto = "tcp"
addr = "172.18.33.125:15140"
chanSize = 10240

[DMerr]
taskID = "1409"
proto = "tcp"
addr = "172.18.33.125:15140"
chanSize = 10240
[host]
    payCenter = "http://pay.bilibili.co"
    liveRpc = "http://rpc.live.bilibili.co"

[httpClient]
     [httpClient.payCenter]
        key = "xHf74ZfV43cAUsUl"
        secret = "d0dbe915091d400bd8ee7f27f0791303"
        dial = "1s"
        timeout = "1s"
        keepAlive = "60s"
        timer = 1000
     [httpClient.liveRpc]
             key = "fb06a25c6338edbc"
             secret = "fd10bd177559780c2e4a44f1fa47fa83"
             dial = "1s"
             timeout = "1s"
             keepAlive = "60s"
             timer = 1000

[gift]
    [gift.rechargeTip]
        silverTipDays = [7]


[liverpc]
    [liverpc.userext]
        Addr = "172.18.33.128:20803"
