version = "1.0.3"

[log]
dir = "/data/log/figure-service"

[bm]
    addr = "0.0.0.0:7062"
    timeout = "1s"
    maxListen = 100

[mysql]
    addr = "172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_figure?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    name = "figure-service"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "720h"

[rpcServer]
    addr = "0.0.0.0:7069"
	proto = "tcp"
    
[property]
    loadRankPeriod = "1m"