[log]
    stdout = true
    # dir = "./log/bbq"
    v = 5

[bm]
    addr = "0.0.0.0:8802"
    timeout = "2s"

[mysql]
	addr = "172.16.38.91:3306"
	dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "800ms"
	execTimeout = "800ms"
	tranTimeout = "1000ms"

[onlineMysql]
	addr = "172.16.38.91:3306"
	dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "800ms"
	execTimeout = "800ms"
	tranTimeout = "1000ms"

[redis]
	name = "bbq-web"
	proto = "tcp"
	addr = "172.16.38.91:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[grpcClient]
    [grpcClient.filter]
		addr = "discovery://default/filter.service"
        [grpcClient.filter.wardenconf]
            dial = "100ms"
            timeout = "500ms"
    [grpcClient.user]
		addr = "discovery://default/bbq.service.user"
        [grpcClient.user.wardenconf]
            dial = "100ms"
            timeout = "500ms"
    [grpcClient.video]
		addr = "discovery://default/bbq.service.video"
        [grpcClient.video.wardenconf]
            dial = "100ms"
            timeout = "500ms"

[antiSpam]
    [antiSpam.bullet]
        on=true
        second=10
        n=8
        hour=1
        m=100

[bulletConfig]
    closeWrite = false
    closeRead = false

[infoc]
    taskID = "001639"
    proto = "tcp"
    addr = "172.18.33.124:15140"
    chanSize = 10240