# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/laser-interface.pid"
dir = "./"
perf = "0.0.0.0:7512"
checkFile = "/data/www/laser-interface.html"

[log]
dir = "/data/log/laser-interface/"

[mysql]
dsn = "root:12345@tcp(127.0.0.1:3306)/bilibili_laser?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 5
idleTimeout = "4h"
queryTimeout = "5s"
execTimeout = "5s"
tranTimeout = "10s"
[mysql.breaker]
window = "30s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100

[bm]
    addr = "0.0.0.0:7510"
    maxListen = 1000
    timeout = "2s"

[identify]
     whiteAccessKey = ""
     whiteMid = 0
     csrf = false
     [identify.app]
     key = "53e2fa226f5ad348"
     secret = "3cf6bd1b0ff671021da5f424fea4b04a"
     [identify.memcache]
     name = "go-business/identify"
     proto = "unix"
     addr = "/tmp/uat-platform-identify-mc.sock"
     active = 10
     idle = 5
     dialTimeout = "1s"
     readTimeout = "1s"
     writeTimeout = "1s"
     idleTimeout = "80s"
     [identify.host]
     auth = "http://uat-passport.bilibili.com"
     secret = "http://uat-open.bilibili.com"
     [identify.httpClient]
     key = "53e2fa226f5ad348"
     secret = "3cf6bd1b0ff671021da5f424fea4b04a"
     dial = "500ms"
     timeout = "800ms"
     keepAlive = "60s"
     [identify.httpClient.breaker]
     window  = "10s"
     sleep   = "100ms"
     bucket  = 10
     ratio   = 0.5
     request = 100
     [identify.httpClient.url]
     "http://uat-passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
     "http://uat-passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
     "http://uat-open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[memcache]
    [memcache.laser]
    name = "creative/archive"
    proto = "tcp"
    addr = "172.16.0.148:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    LaserExpire = "60s"

[mail]
     host = "smtp.exmail.qq.com"
     port = 465
     username = "2333@bilibili.com"
     password = "233"
