# This is a TOML document. Boom.

version = "1.0.0"


[bm]
	addr = "0.0.0.0:6991"
	timeout = "1s"

[rpcClient]
	[rpcClient.member]
	    timeout = "1s"
	[rpcClient.account]
		timeout = "10s"

[mysql]
    addr = "127.0.0.1:3306"
    dsn = "root:123456@tcp(127.0.0.1:3306)/bilibili_answer?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1000ms"
    execTimeout = "1000ms"
    tranTimeout = "2000ms"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[memcache]
    name = "answer"
    proto = "tcp"
    addr = "172.18.33.60:11234"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"
    answerBolckExpire = "12h"

[redis]
    name = "answer"
	proto = "tcp"
	addr = "127.0.0.1:6379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "720h"
    ansCountExpire = "12h"
    ansAddFlagCountExpire = "1m"
    
[Captcha]
    key = "c1a1cb2d89c33794"
    secret = "dda47eeca111e03e6845017505baea13"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [Captcha.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100


[httpClient]
    [httpClient.normal]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"
    [httpClient.normal.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.slow]
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
    key = "zxnh4k92dwe61t27"
    secret = "dnu3bwpxyswqwf1ixpsczthury1nqiew"
    [httpClient.slow.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[host]
    api     = "http://api.bilibili.co"
    geetest = "http://api.geetest.com"
    account = "http://account.bilibili.com"
    extraIds = "http://172.18.33.147:3000/laogai/question/exam/danmu"

[geetest]
    [geetest.PC]
    captchaId = "a703e7d11eda930ca87be02c1a80ff97"
    privateKey = "df5eacf78b4afc79a052f199939e946a"
    [geetest.H5]
    captchaId = "bf666f87e5cca24ddb4c1dbeb70912b8"
    privateKey = "d1e0bc5eadc754f8cd522c6fed5e175d"

[infoc2]
    taskID = "000078"
    proto = "tcp"
    addr = "172.19.100.20:5401"
    chanSize = 1024

[dataBus]
[dataBus.extraAnswer]
    key = "0QEO9F8JuuIxZzNDvklH"
    secret= "0QEO9F8JuuIxZzNDvklI"
    group= "AccAnswer-BigData-P"
    topic= "AccAnswer-T"
    action="pub"
    name = "answer-interface/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
[dataBus.accountFormal]
    key = "875d05ffa843e297"
    secret= "24d052bae2247fc59ee925d46ffd61e2"
    group= "Answer-MainAccountLaw-P"
    topic= "Answer-T"
    action="pub"
    name = "answer-interface/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[antispam]
	on=true
	second=2
	n=1
	hour=12
	m=5
[antispam.redis]
	name = "answer"
	proto = "tcp"
	addr = "172.16.33.54:6379"
	idle = 100
	active = 100
	dialTimeout = "500ms"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "80s"
	expire = "10m"
    
[answer]
    debug=true
    duration=30
    blockedTimestamp=0
    baseNum = 4
    proNum = 5
    baseExtraPassNum=5
    baseExtraNoPassNum=5
    baseExtraScore=2
    baseExtraPassCount=3
    extraNum = 10
    maxRetries = 10
    captchaTokenURL = "http://api.bilibili.co/x/internal/v1/captcha/token"
    captchaVerifyURL = "http://api.bilibili.co/x/internal/v1/captcha/verify"

[question]
    tcQestTick = "1m"
    rankQestTick = "10m"

[backoff]
    maxDelay = 60
    baseDelay = 5
    factor = 1.6
    jitter = 0.2