refreshTime = 30

[log]
stdout=true

[httpClient]
key = "c1a1cb2d89c33794"
secret = "dda47eeca111e03e6845017505baea13"
dial = "300ms"
timeout = "800ms"
keepAlive = "60s"
timer = 512
[httpClient.url]
"https://api.bilibili.co/x/internal/v2/reply/ishot" = {timeout="200ms"}
[httpClient.breaker]
window  = "10s"
sleep   = "50ms"
bucket  = 10
ratio   = 0.5
request = 100

[mysql]
    [mysql.db]
    addr = "172.22.34.101:3306"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_reply?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active = 10
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [mysql.db.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [mysql.dbSlave]
    addr = "172.22.34.101:3306"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_reply?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active = 10
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [mysql.dbSlave.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
	name = "reply-feed-job"
	proto = "tcp"
	addr = "172.18.33.60:6889"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[redisExpire]
    redisReplySetExpire = "12h"
    redisReplyZSetExpire = "12h"
    redisRefreshExpire = "12h"

[memcache]
	name = "reply-feed-job"
	proto = "tcp"
	addr = "172.18.33.61:11213"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

 [memcacheExpire]
    mcStatExpire = "12h"

[databus]
    [databus.event]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "ReplyFeed-MainCommunity-S"
    topic = "ReplyFeed-T"
    action ="sub"
    name = "reply-feed/event"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 2
    active = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "1h"
    [databus.stats]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "Reply-MainCommunity-S"
    topic = "Reply-T"
    action ="sub"
    name = "reply/stats"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 2
    active = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "1h"
