[bm]
    [bm.inner]
    addr = "0.0.0.0:6951"
    maxListen = 1000
    timeout = "1s"

[httpClient]
    [httpClient.normal]
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
       key = "e7482d29be4a95b8"
        secret = "9e803791cdef756e75faee68e12b7442"
    [httpClient.normal.host]
    "http://cm.bilibili.co" = {key = "test",secret = "e6c4c252dc7e3d8a90805eecd7c73396"}
    [httpClient.normal.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
    [httpClient.slow]
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
       key = "e7482d29be4a95b8"
        secret = "9e803791cdef756e75faee68e12b7442"
    [httpClient.slow.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[rpcClient2]
    [rpcClient2.member]
        color = "group1"
        timeout = "150ms"
   [rpcClient2.account]
        color = "group2"
        timeout = "200ms"
    [rpcClient2.archive]
        timeout = "100ms"
    [rpcClient2.relation]
        token="test"
        timeout = "1s"
    [rpcClient2.usersuit]
        timeout = "1s"
    [rpcClient2.article]
        timeout = "1s"
    [rpcClient2.up]
        timeout = "1s"
        group = "test"
    [rpcClient2.passport]
        timeout = "1s"
    [rpcClient2.coin]
        timeout = "1s"
    [rpcClient2.location]
        timeout = "1s"
    [rpcClient2.secure]
        timeout = "1s"
    [rpcClient2.vip]
        timeout = "200ms"

[app]
key = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[antispam]
    on=true
    second=2
    n=1
    hour=12
    m=500
    [antispam.redis]
        name = "member/account-interface"
        proto = "tcp"
        addr = "172.16.33.54:6379"
        active = 5
        idle = 5
        dialTimeout = "90ms"
        readTimeout = "100ms"
        writeTimeout = "100ms"
        idleTimeout = "80s"
        expire = "24h"

[smsantispam]
    on=true
    second=60
    n=1
    hour=1
    m=10
    [smsantispam.redis]
        name = "member/member-interface"
        proto = "tcp"
        addr = "172.16.33.54:6379"
        idle = 5
        active = 5
        dialTimeout = "500ms"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"
        expire = "10m"

[vipantispam]
    on=true
    second=1
    n=2
    hour=1
    m=10
    [vipantispam.redis]
        name = "member/member-interface"
        proto = "tcp"
        addr = "172.16.33.54:6379"
        idle = 5
        active = 5
        dialTimeout = "500ms"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"
        expire = "10m"

[host]
    acccom = "http://account.bilibili.com"
    accco = "http://uat-account.bilibili.co"
    passport = "http://passport.bilibili.co"
    api = "http://api.bilibili.co"
    vip = "http://vip.bilibili.co"
    www = "http://www.bilibili.com"
    search = "http://s.search.bilibili.co"
    cm = "http://cm.bilibili.co"
    passportCom = "https://passport.bilibili.com"

[VipProperty]
    CodeOpenwhiteIPMap={"b2cf4e9dbe9fd2e3"=["111.203.12.97","111.203.12.98","123.125.99.176","123.125.99.177","123.125.99.178","123.125.99.179","123.125.99.180"],"6e8687402f1ab860"=["219.135.155.76","134.175.201.88"]}
    EleOAuthURI="https://open.faas.ele.me/docs/8cd9ba96ee0a53a1fd2c6d84d15727eebd8aa054"
    EleConsumerKey="4400479257"
    EleOAuthCallBackURI="https://api.bilibili.com/x/oauth2/v1/callback"
    ActivityURI="https://uat-www.bilibili.com/blackboard/preview/activity-E2yZx8RLI.html?time=1545580800000"
    ActStartTime = 1144488082
    ActEndTime = 1154488082
    [VipProperty.OAuthClient]
        key = "ad4bb9b8f5d9d4a7"
        secret = "6912080d78d58be7cb94f57d50d438f6"

[accmemcache]
    name = "account-interface"
    proto = "tcp"
    addr = "172.18.33.61:11212"
    idle = 5
    active = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[realname]
    dataDir = "/idenfiles"
	imageExpire = "1m"
    alipayAntispamTTL = 86400
    alipayAntispamThreshold = 0
    [realname.geetest]
        registerURL = "http://api.geetest.com/register.php"
        validateURL = "http://api.geetest.com/validate.php"
        captchaID = "e81f58b498a0106eb92b985aef20a15f"
        privateKey = "a6ccb3f6865c9fabaaa57c8cee5a7609"
    [realname.alipay]
        gateway = "https://openapi.alipay.com/gateway.do"
        appID = "2018062060353784"
    [[realname.channel]]
        name = "main"
        flag = true
    [[realname.channel]]
        name = "alipay"
        flag = true

[nickFreeAppKeys]
    aaaa= ""

[SMSAntispam]
	on=true
	second=2
	n=1
	hour=12
	m=5
[SMSAntispam.redis]
	name = "answer"
	proto = "tcp"
	addr = "172.16.33.54:6379"
	idle = 100
	active = 100
	dialTimeout = "500ms"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "80s"
	expire = "10m"

[bfs]
    timeout="500ms"
    maxFileSize=8388608
    bucket="b"
    url="http://bfs.bilibili.co/bfs/"
    method="PUT"
    key="25bf7f1ec06cf75a"
    secret="dba1dc9d43472cced48b9dc9816a46"
    faceBucket="face"
    facekey="792d70f16e958493"
    facesecret="08525fe929bdb26c3a6009afd7318f"

[facebfs]
    timeout="500ms"
    maxFileSize=8388608
    url="http://bfs.bilibili.co/bfs/"
    method="PUT"
    bucket="face"
    key="792d70f16e958493"
    secret="08525fe929bdb26c3a6009afd7318f"

[faceantispam]
    on=true
    second=60
    n=10
    hour=1
    m=100
    [faceantispam.redis]
        name = "member/account-interface"
        proto = "unix"
        addr = "/tmp/uat-redisantispam-redis.sock"
        active = 10
        idle = 1
        dialTimeout = "90ms"
        readTimeout = "100ms"
        writeTimeout = "100ms"
        idleTimeout = "80s"
        expire = "24h"
[switch]
    updatePropertyPhoneRequired = true

[geetest]
    [geetest.PC]
    captchaId = "a703e7d11eda930ca87be02c1a80ff97"
    privateKey = "df5eacf78b4afc79a052f199939e946a"
    [geetest.H5]
    captchaId = "bf666f87e5cca24ddb4c1dbeb70912b8"
    privateKey = "d1e0bc5eadc754f8cd522c6fed5e175d"

[Account]
RemoveLoginLogCIDR = ["222.73.196.18/28", "121.46.231.66/29", "61.130.181.50/28", "61.244.26.110/30", "103.36.115.65/32", "114.134.80.196/32", "218.189.16.245/32", "202.153.91.146/32", "202.153.91.76/32", "202.153.91.97/32", "103.193.127.56/32", "116.211.6.86/30", "123.124.149.6/32", "36.112.7.18/32"]

[accountnotify]
key = "4ba46ba31f9a44ef"
secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
group = "AccountNotify-MainAccount-P"
topic = "AccountNotify-T"
action = "pub"
buffer = 2048
name = "account-notify-job/databus"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[BatchRelAntispam]
    on=true
    second=2
    n=1
    hour=1
    m=10
    [BatchRelAntispam.redis]
        name = "member/account-interface"
        proto = "unix"
        addr = "/tmp/uat-redisantispam-redis.sock"
        active = 10
        idle = 1
        dialTimeout = "90ms"
        readTimeout = "100ms"
        writeTimeout = "100ms"
        idleTimeout = "80s"
        expire = "24h"

[vipThirdVerifyConfig]
    authAppkeyMap = {"7xio6i8k93i5e4er"="lc1cqoasuxpeodvkwg5xkemell2eavwa"}
