spLimit = "500ms"
hashNum = 1000000
monitorURL = true
monitorArchive = true
WeChatToken = "uYsRqXPjnbyXDCba"
WeChatSecret = "tUILeGIXJHFSUdwfLjBHDZJXmLgYpgEy"
WeChantUsers = ["zhaobingqing"]

[reload]
ad="10s"

[note]
noteNumber = 4

[Host]
bangumi  = "http://bangumi.bilibili.com"
ad       = "http://cm.bilibili.co"
dataPlat = "http://172.18.33.162:6193"

[xlog]
dir = "/data/log/resource-service/"

[httpClient]
key     = "f022126a8a365e20"
secret  = "b7b86838145d634b487e67b811b8fab2"
dial = "500ms"
timeout = "2s"
keepAlive = "60s"
timer = 1000
    [httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.1
    request = 10

[bm]
    [bm.inner]
    addr = "0.0.0.0:6421"
    timeout = "1s"
    [bm.local]
    addr = "0.0.0.0:6423"
    timeout = "1s"

[rpcServer2]
[[rpcServer2.servers]]
    proto = "tcp"
    addr = "0.0.0.0:6429"
    weight = 10 
[rpcServer2.zookeeper]
    root = "/microservice/resource-service/"
    addrs = ["172.18.33.50:2199","172.18.33.51:2199","172.18.33.52:2199"]
    timeout = "30s"

[db]
    [db.res]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.res.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.ads]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_ads?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.ads.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.show]
    addr   = "172.16.33.205:3308"
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle   = 1
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.show.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.manager]
    addr   = "172.16.33.205:3308"
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_manager?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle   = 1
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.manager.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    [redis.ads]
    name = "resource-service"
    proto = "tcp"
    #addr = "172.16.33.54:6379"
    addr = "172.18.33.60:6975"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "1m"

[archiveSub]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "Archive-MainAppSvr-2-S"
    topic = "Archive-T"
    action = "sub"
    name = "archive-job/archivesub"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
