# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/workflow-admin.pid"
dir = "./"
family = "workflow-admin"
chanSize = 1024

[log]
dir = "/data/log/workflow-admin"

[multiHTTP]
    [multiHTTP.inner]
    addrs = ["0.0.0.0:7211"]
    [multiHTTP.local]
    addrs = ["0.0.0.0:7212"]

[bm]
    addr = "0.0.0.0:7211"
    maxListen = 1000
    timeout = "10s"

[orm]
    [orm.write]
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_workflow?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 10
    idleTimeout = "4h"
    [orm.read]
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_workflow?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 10
    idleTimeout = "4h"

[db]
    [db.workflow]
    name = "172.22.16.3:3459"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_workflow?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 10
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.workflow.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.workflowread]
    name = "172.22.16.3:3459"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_workflow?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 10
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.workflowread.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[identify]
    [identify.host]
    auth = "http://uat-passport.bilibili.co"
    secret = "http://uat-open.bilibili.co"
    [identify.HTTPClient]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "100ms"
    timeout = "200ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[host]
searchURL = "http://uat-bili-search.bilibili.co"
#searchURL = "http://127.0.0.1:18080"
reviewURL = "https://uat-bangumi-mng.bilibili.co"
platformURL = "http://uat-api.bilibili.co"
messageURL = "http://uat-message.bilibili.co"
unameURL = "http://uat-manager.bilibili.co/x/admin/manager/users/unames"
uidURL = "http://uat-manager.bilibili.co/x/admin/manager/users/uids"
pgcURL = "http://uat-bangumi-mng.bilibili.co/media/internal/review/views"
archiveURL = "http://uat-archive.api.bilibili.co/videoup/views"
accountURL = "http://uat-api.bilibili.co/x/internal/v3/account/profile/stat"
archivetypesURL = "http://uat-archive.api.bilibili.co/videoup/types"
upergroupURL = "http://uat-api.bilibili.co/x/internal/uper/special/get"
relationURL = "http://uat-api.bilibili.co/x/internal/relation/stats"
businessListURL = "http://uat-manager.bilibili.co/x/admin/manager/internal/business/list"
userListURL = "http://uat-manager.bilibili.co/x/admin/manager/business/user/list"
tagListURL = "http://uat-manager.bilibili.co/x/admin/manager/internal/tag/list"
channelInfoURL = "http://uat-api.bilibili.co/x/internal/channel/resource/checkback"
businessRoleURL = "http://uat-manager.bilibili.co/x/admin/manager/internal/business/role"
blockURL = "http://uat-api.bilibili.co/x/internal/block/batch/block"
creditBlockedURL = "http://uat-api.bilibili.co/x/internal/credit/blocked/info/add"
blockInfoURL = "http://uat-api.bilibili.co/x/internal/block/info"
blockNumURL = "http://uat-api.bilibili.co/x/internal/credit/blocked/user/num"
blockCaseAddURL = "http://uat-api.bilibili.co/x/internal/credit/blocked/case/add"

[httpClient]
   [httpClient.read] 
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "50ms"
    timeout = "3s"
    keepAlive = "60s"
    timer = 16
    [httpClient.read.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.write]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "50ms"
    timeout = "3s"
    keepAlive = "60s"
    timer = 16
    [httpClient.write.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.18.33.61:11232"
    active = 10
    idle = 10
    dialTimeout = "5s"
    readTimeout = "5s"
    writeTimeout = "5s"
    idleTimeout = "80s"

[memcache]
    proto = "tcp"
    addr = "172.18.33.60:11236"
    idle = 10
    active = 10
    dialTimeout = "2s"
    readTimeout = "2s"
    writeTimeout = "2s"
    idleTimeout = "7h"
    expireCount = "10s"
	expireOnline = "0s"
	
[redis]
	proto = "tcp"
	addr = "172.18.33.61:6889"
	idle = 10
	active = 10
	dialTimeout = "500ms"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "80s"
	expire = "0s"

[elastic]
host = "http://uat-manager.bilibili.co"
[elastic.HTTPClient]
    key = "3c4e41f926e51656"
    secret = "26a2095b60c24154521d24ae62b885bb"
    dial = "1s"
    timeout = "2s"
    keepAlive = "60s"
    timer = 1000
    [elastic.HTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[accountRPC]
    timeout = "2s"

[archiveRPC]
     timeout = "2s"
