
[bm]
 addr = "0.0.0.0:9001"
 timeout = "10s"

[httpClient]
    key = "c05dd4e1638a8af0"
    secret = "7daa7f8c06cd33c5c3067063c746fdcb"
    dial = "2s"
    timeout = "100s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  = "10s"
    sleep   = "2000ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[tapd]
WorkspaceIDs = ["20060791","20055921"]


IterationWorkspaceIDs = ["20060791","20055921","20082211"]
StoryWorkspaceIDs = ["20060791","20055921"]
BugWorkspaceIDs = ["20082211"]

IPS  = 30
SPS  = 30
SCPS = 50
CPS  = 50
StoryFilePath = "story.txt"
ChangeFilePath = "change.txt"
IterationFilePath = "iteration.txt"
BugFilePath = "bug.txt"
retryTime = 5
waitTime = "10s"


[scheduler]
#每天凌晨2点跑拉取数据任务
saveTapdTime = "0 0 2 * * ?"

[mail]
host = "smtp.exmail.qq.com"
port = 465
username = "merlin@bilibili.com"
password = ""
noticeOwner = ["fengyifeng@bilibili.com"]

[memcache]
	name = "merlin"
	proto = "tcp"
	addr = "172.22.33.137:11216"
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "12h"

[bugly]
host = "https://bugly.qq.com"
cookie = "D:\\fyf\\code5\\bugly-dailyrun\\conf\\cookie.conf"
token  = "D:\\fyf\\code5\\bugly-dailyrun\\conf\\token.conf"
version = "D:\\fyf\\code5\\bugly-dailyrun\\conf\\version.conf"

[bugly2tapd]
projectIds = ["900028525"]

[orm]
dsn = "root:123456@tcp(172.18.33.130:3306)/footman?timeout=200ms&readTimeout=2000ms&writeTimeout=2000ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 5
idleTimeout = "4h"