[grpc]
    timeout = "6s"

[httpClient]
    key    = "cadf599ba8b3796a"
    secret = "42fbb979aa742013d713a088f912673b"
    dial      = "6s"
    timeout   = "6s"
    keepAlive = "60s"
    timer = 10
    [httpClient.breaker]
        window  = "10s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[memcache]
    name = "tv"
    proto = "tcp"
    addr = "127.0.0.1:11231"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "36h"
    relateExpire  = "20m"
    arcExpire  = "20m"
    viewExpire = "20m"
    cmsExpire = "36h"
    cacheExpire   = "1h"
    hisExpire = "3m"
    mangoExpire = "10m"

[accountRPC]
    timeout = "1s"

[mysql]
    addr= "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_tv?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "2000ms"
    execTimeout = "2000ms"
    tranTimeout = "5000ms"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[pay]
    payExpireDuration = "4h"
    renewFromDuration = "48h"
    renewToDuration = "24h"
    qrURL = "http://callback-api.bilibili.cn/x/tv/vip/order/create"
    guestQrURL = "http://callback-api.bilibili.cn/x/tv/vip/order/create"

[cacheTTL]
    userInfoTTl = 1800
    payParamTTL = 900
    
[yst]
    key = "snm112901*!lkkjWngso4%*&o+-(j242Ssdrfslj"
    domain = "gwboss.test.atianqi.com:443/boss/inter/bili"

[mvip]
    BatchUserInfoUrl = "http://api.bilibili.co/x/internal/big/useBatchInfo"
    [mvip.BatchIdsMap]
    1 = 21
    23 = 21

[ticker]
    panelRefreshDuration = "5s"
    unpaidDurationStime = "25m"
    unpaidDurationEtime = "30m"
    unpaidRefreshDuratuion = "30s"