# This is a TOML document. Boom.
version = "0.0.2"
user = "nobody"
pid = "/tmp/ticket-sales.pid"
dir = "/data/log"
perf = "0.0.0.0:3013"
family = "ticket-sales"
address = "127.0.0.1"
env = "dev"

[log]
	dir = "/tmp/log/ticket-sales"
	v = 3

[db]
    [db.master]
    name = "172.16.33.203:3306"
    dsn = "root:123456@tcp(172.16.33.203:3306)/tickets?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    #dsn = "test_3310:Lb1XsyqV6ZjY34tPKcAdHGapuxi9vowr@tcp(172.22.34.101:3310)/open_ticket?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [db.master.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    [redis.master]
    name = "ticket-service"
    proto = "tcp"
    addr = "172.16.33.203:9379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "10s"

[httpClient]
  [httpClient.read]
  key = "7c7ac0db1aa05587"
  secret = "9a6d62d93290c5f771ad381e9ca23f26"
  dial = "1s"
  timeout = "4s"
  keepAlive = "60s"
  timer = 1000
  [httpClient.read.breaker]
      window  = "3s"
      sleep   = "100ms"
      bucket  = 10
      ratio   = 0.5
      request = 100
  [httpClient.write]
  key = "7c7ac0db1aa05587"
  secret = "9a6d62d93290c5f771ad381e9ca23f26"
  dial = "1s"
  timeout = "3s"
  keepAlive = "60s"
  timer = 1000
  [httpClient.write.breaker]
      window  = "3s"
      sleep   = "100ms"
      bucket  = 10
      ratio   = 0.5
      request = 100

[app]
    key = "7d9f6f6fe2a898e8"
    secret = "test"

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    csrfOn = false
    [identify.app]
    key = "7d9f6f6fe2a898e8"
    secret = "test"
    [identify.host]
    auth = "http://uat-passport.bilibili.co"
    secret = "http://uat-open.bilibili.co"
    [identify.httpClient]
    key = "7d9f6f6fe2a898e8"
    secret = "test"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://uat-passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://uat-passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://uat-open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[ut]
    distPrefix  = "http://localhost:8801/x/internal/ticket/sales"

[encrypt]
    key = "bilibili_key_GYl"
    iv = "biliBiliIv123456"

[urls]
    basecenter = "http://uat-show.bilibili.co/api/basecenter"

[basecenter]
    appId = "nBF6jpB7"
    token = "XZUGqmAf1rRmu7l0dhogFIPPvveHOgSy2WtQ957JPeE="

[grpcClient]
    [grpcClient.item]
        dial = "1000ms"
        timeout = "5000ms"
    [grpcClient.account]
        dial = "1000ms"
        timeout = "5000ms"

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://uat-dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[testProject]
ids = [10005, 10001, 425]
# querystring需要带这个参数才可以访问到
check_query = "1e1a4e8ca5a787226ce7a50535764651"

[databus]
    [databus.update]
    key = "39143bf7b888273e"
    secret= "0766c43df93a9204d81c46caf2231ee1"
    group= "TicketItemUpdate-OpenTicket-P"
    topic= "TicketItemUpdate-T"
    action="pub"
    name = "databus/update"
    proto = "tcp"
    addr = "172.16.38.154:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"