# This is a TOML document. Boom

[log]
stdout=true

[orm]
[orm.read]
    dsn = "account:wx2U1MwXRyWEuURw@tcp(172.16.33.205:3306)/relation?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 20
    idle = 10
    idleTimeout = "4h"

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://uat-dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 10
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[RelationGRPC]
timeout="3s"

[AccountGRPC]
timeout="3s"

[loghbase]
    master = ""
    meta = ""
    dialTimeout = "1s"
    readTimeout = "10s"
    readsTimeout = "10s"
    writeTimeout = "10s"
    writesTimeout = "10s"
        [loghbase.zookeeper]
        root = ""
        addrs =["bigdata-test-02:2181","bigdata-test-03:2181","bigdata-test-04:2181"]
        timeout = "30s"