[log]
    stdout=true

[liveUserMysql]
	addr = "172.16.38.117:3312"
	dsn = "live:oWni@ElNs0P0C(dphdj*F1y4@tcp(172.16.38.117:3312)/live-user?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["live:oWni@ElNs0P0C(dphdj*F1y4@tcp(172.16.38.117:3312)/live-user?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "5s"
	execTimeout = "5s"
	tranTimeout = "5s"

[UserExpMySQL]
    addr = "172.22.34.101:3312"
    dsn = "livetestuat:livetestuat20180711/live_user_exp?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN = ["livetestuat:livetestuat20180711@tcp(172.22.34.101:3312)/live_user_exp?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "2s"
    execTimeout = "2s"
    tranTimeout = "5s"


[ExpMemcache]
	name = "xuser-service"
	proto = "tcp"
	addr = "172.18.33.82:11211"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[Switch]
    QueryExp = 1

[UserExpExpire]
    ExpireTime = 86400


[vipRedis]
	name = "xuser-vip-redis"
	proto = "tcp"
	addr = "127.0.0.1:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[guardRedis]
	name = "xuser-vip-redis"
	proto = "tcp"
	addr = "127.0.0.1:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[bmClient]
    key = "837f620f5c0a8010"
    secret = "2a9057021014b4b843b635664c69d5df"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    [httpClient.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[liveRPC]
    [liverpc.room]
        AppID = "live.room"
        ConnTimeout = "50ms"
        Addr = "172.18.33.82:20200"

    [liverpc.user]
        AppID = "live.user"
        ConnTimeout = "50ms"
        Addr = "172.18.33.82:20802"

    [liverpc.banned]
        AppID = "live.banned"
        ConnTimeout = "50ms"
        Addr = "172.18.33.82:20822"

    [liverpc.fans_medal]
        AppID = "live.fansmedal"
        ConnTimeout = "50ms"
        Addr = "172.18.33.82:20800"


[liveVipChangePub]
    key = "ec4c0820d525d67b"
    secret = "2bdf3bd4ecab041b5d5640a1da4f7f81"
    group = "LiveVipChange-LiveLive-P"
    topic = "LiveVipChange-T"
    action = "pub"
    buffer = 128
    name = "xuser-vip/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[liveEntryEffectPub]
    key = "ec4c0820d525d67b"
    secret = "e20f8f664bf10722efeb6aac0cc16011"
    group = "LiveEntryEffect-LiveLive-P"
    topic = "LiveEntryEffect-T"
    action = "pub"
    buffer = 128
    name = "xuser-guard/databus"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[liveAppMySQL]
	addr = "172.22.34.101:3312"
	dsn = "livetestuat:livetestuat20180711@tcp(172.22.34.101:3312)/live-app?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["live:livetestuat20180711@tcp(172.22.34.101:3312)/live-app?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "2s"
	execTimeout = "2s"
	tranTimeout = "5s"

[liveAppORM]
	addr = "172.22.34.101:3312"
	dsn = "livetestuat:livetestuat20180711@tcp(172.22.34.101:3312)/live-app?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["live:livetestuat20180711@tcp(172.22.34.101:3312)/live-app?timeout=2s&readTimeout=2s&writeTimeout=2s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "2s"
	execTimeout = "2s"
	tranTimeout = "5s"

[redis]
	name = "xuser-redis"
	proto = "tcp"
    addr = "127.0.0.1:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[memcache]
	name = "xuser-memcache"
	proto = "tcp"
	addr = "127.0.0.1:11211"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"
