# This is a TOML document. Boom

version = "1.0.0"
user = "nobody"
pid = "/tmp/stress.pid"
dir = "./"
perf = "0.0.0.0:6420"
trace = false
debug = false


[log]
vLevel = 1

[tracer]
proto = "udp"
addr = "172.16.33.46:5140"
tag = "mypro"

[bm]
	[bm.inner]
	addr = "0.0.0.0:9001"
	timeout = "1s"
	[bm.local]
	addr = "0.0.0.0:9002"
	timeout = "1s"

[identify]
	whiteAccessKey = ""
	whiteMid = 0
	[identify.app]
	key = "6a29f8ed87407c11"
	secret = "d3c5a85f5b895a03735b5d20a273bc57"
	[identify.memcache]
	name = "go-business/identify"
	proto = "tcp"
	addr = "172.16.33.54:11211"
	active = 5
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "80s"
	[identify.host]
	auth = "http://passport.bilibili.com"
	secret = "http://open.bilibili.com"
	[identify.httpClient]
	key = "f022126a8a365e20"
	secret = "b7b86838145d634b487e67b811b8fab2"
	dial = "30ms"
	timeout = "100ms"
	keepAlive = "60s"
	[identify.httpClient.breaker]
	window  = "10s"
	sleep   = "100ms"
	bucket  = 10
	ratio   = 0.5
	request = 100
	[identify.httpClient.url]
	"http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
	"http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
	"http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[ecode]
	domain = "uat-api.bilibili.co"
	all = "1h"
	diff = "5m"
	[ecode.clientconfig]
		key = "c1a1cb2d89c33794"
		secret = "dda47eeca111e03e6845017505baea13"
		dial      = "2000ms"
		timeout   = "2s"
		keepAlive = "10s"
		timer     = 128
		[ecode.clientconfig.breaker]
			window  ="3s"
			sleep   ="100ms"
			bucket  = 10
			ratio   = 0.5
			request = 100

[mysql]
	addr = "127.0.0.1:3306"
	dsn = "test:test@tcp(127.0.0.1:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["test:test@tcp(127.0.0.2:3306)/test? timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4","test:test@tcp(127.0.0.3:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"
	[mysql.breaker]
	window = "3s"
	sleep = "100ms"
	bucket = 10
	ratio = 0.5
	request = 100
[redis]
	name = "stress"
	proto = "tcp"
	addr = ""
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[memcache]
	name = "stress"
	proto = "tcp"
	addr = ""
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

