version = "1.0.0"
user    = "nobody"
pid     = "/tmp/app-job.pid"
dir     = "./"
perf    = "0.0.0.0:6670"
family = "app-job"
trace   = false
debug   = false
env     = "test"
tick    = "5m"

[view]
flush = true

[xlog]
dir = "/data/log/app-job/"

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[host]
app      = "http://app.bilibili.com"
config   = "http://config.bilibili.co:9011"
hetongzi = "http://hetongzi.bilibili.co"
apiCo    = "http://api.bilibili.co"

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "1s"
keepAlive = "60s"
timer     = 128
[httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpClientAsyn]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "1s"
timeout   = "2s"
keepAlive = "60s"
timer     = 10
[httpClientAsyn.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[bm]
    [bm.inner]
    addr = "0.0.0.0:6671"
    timeout = "1s"

[mysql]
	[mysql.show]
    addr   = "172.16.33.205:3308"
	dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle   = 2
    idleTimeout ="4h"
    queryTimeout = "150ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.show.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[archiveNotifySub]
key = "0QEO9F8JuuIxZzNDvklH"
secret = "0QEO9F8JuuIxZzNDvklI"
group = "ArchiveNotify-App-S"
topic = "ArchiveNotify-T"
action = "sub"
name = "app-job/archiveNotifysub"
proto = "tcp"
addr = "172.16.33.158:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[accountNotifySub]
key = "0QEO9F8JuuIxZzNDvklH"
secret = "0QEO9F8JuuIxZzNDvklI"
group = "AccountNotify-App-S"
topic = "AccountNotify-T"
action = "sub"
name = "app-job/accountNotifysub"
proto = "tcp"
addr = "172.16.33.158:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[statViewSub]
key = "0Pub71WwEMKXu63qtztu"
secret = "0Pub71WwEMKXu63qtztv"
group = ""
topic = "StatView-T"
action = "sub"
offset = "old"
buffer = 128
name = "app-job/stat"
proto = "tcp"
addr = "172.16.33.158:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[memcache]
    [memcache.feed]
    name   = "app-job/feed"
    proto  = "tcp"
    addr   = "172.16.33.54:11213"
    active = 50
    idle   = 10
    dialTimeout  = "50ms"
    readTimeout  = "100ms"
    writeTimeout = "100ms"
    idleTimeout  = "80s"
    expireArchive = "2h"

[redis]
    [redis.feed]
    name   = "app-feed/feed"
    proto  = "tcp"
    addr   = "172.16.0.148:6379"
    active = 20
    idle   = 10
    dialTimeout  = "50ms"
    readTimeout  = "100ms"
    writeTimeout = "100ms"
    idleTimeout  = "80s"
    [redis.Contribute]
    name   = "app-feed/Contribute"
    proto  = "tcp"
    addr   = "172.16.0.148:6379"
    active = 20
    idle   = 10
    dialTimeout  = "50ms"
    readTimeout  = "100ms"
    writeTimeout = "100ms"
    idleTimeout  = "80s"