[log]
    stdout = true
    v = 5

[mysql]
	addr = "172.16.38.91:3306"
	dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "800ms"
	execTimeout = "800ms"
	tranTimeout = "100ms"
[dmmysql]
    addr = "172.16.38.91:3306"
    dsn = "root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN = ["root:123456@tcp(172.16.38.91:3306)/bbq?allowNativePasswords=true&timeout=800ms&readTimeout=1200ms&writeTimeout=800ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "800ms"
    execTimeout = "800ms"
    tranTimeout = "1000ms"

[redis]
	name = "bbq-dev"
	proto = "tcp"
	addr = "172.16.38.91:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[httpClient]
    [httpClient.normal]
        dial = "500ms"
        timeout = "1s"
        keepAlive = "60s"
        timer = 10
        key = "c8c48e784e05acfb"
        secret = "aa63ee0a10afa358d02a07e7abcec546"
    [httpClient.normal.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
    [httpClient.slow]
        dial = "500ms"
        timeout = "1s"
        keepAlive = "60s"
        timer = 10
        key = "c8c48e784e05acfb"
        secret = "aa63ee0a10afa358d02a07e7abcec546"
    [httpClient.slow.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[grpcClient]
    [grpcClient.account]
		addr = "discovery://default/account.service"
        [grpcClient.account.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.recsys]
        addr = "discovery://default/bbq.service.recsys"
        [grpcClient.recsys.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.bbqes]
		addr = "discovery://default/bbq.service.search"
		[grpcClient.bbqes.wardenconf]
        	dial = "100ms"
        	timeout = "5000ms"
    [grpcClient.videoimage]
        addr = "discovery://default/bbq.service.image"
        [grpcClient.videoimage.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.bvcplay]
        addr = "172.16.39.21:14500"
        [grpcClient.bvcplay.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.notice]
        addr = "discovery://default/bbq.service.notice"
        [grpcClient.notice.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.user]
        addr = "discovery://default/bbq.service.user"
        [grpcClient.user.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.sysmsg]
        addr = "discovery://default/bbq.service.sysmsg"
        [grpcClient.sysmsg.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.video]
        addr = "discovery://default/bbq.service.video"
        [grpcClient.video.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"
    [grpcClient.filter]
		addr = "discovery://default/filter.service"
        [grpcClient.filter.wardenconf]
            dial = "3000ms"
            timeout = "5000ms"

[antiSpam]
    [antiSpam.relation]
        on=true
        second=3
        n=3
        hour=1
        m=500
    [antiSpam.like]
        on=true
        second=1
        n=2
        hour=1
        m=500
    [antiSpam.reply]
        on=true
        second=10
        n=8
        hour=1
        m=100
    [antiSpam.upload]
        on=true
        second=3
        n=1
        hour=1
        m=20
    [antiSpam.report]
        on=true
        second=1
        n=5
        hour=1
        m=30

[subTitleCfg]
    user_base = 1
    user_collection = 1
    user_fan = 1
    user_follow = 1
    user_like = 1

[tmap]
    1=   "动画"
    3=   "音乐"
    4=   "游戏"
    5=   "娱乐"
    11=  "电视剧"
    13=  "番剧"
    23=  "电影"
    36=  "科技"
    119= "鬼畜"
    129= "舞蹈"
    155= "时尚"
    160= "生活"
    165= "广告"
    167= "国创"
    177= "纪录片"
    181= "影视"
    
[urls]
    bvc_batch = "http://bvc-vod.bilibili.co/playurl/batch"
    reply_cursor = "http://uat-api.bilibili.co/x/v2/reply/cursor"
    reply_add = "http://uat-api.bilibili.co/x/v2/reply/add"
    reply_list = "http://uat-api.bilibili.co/x/v2/reply"
    reply_subcursor = "http://uat-api.bilibili.co/x/v2/reply/reply/cursor"
    reply_report = "http://uat-api.bilibili.co/x/v2/reply/reply/report"
    reply_like = "http://uat-api.bilibili.co/x/v2/reply/action"
    account = "http://uat-api.bilibili.co/x/internal/v3/account/info"
    reply_counts = "http://uat-api.bilibili.co/x/internal/v2/reply/counts"
    reply_minfo = "http://uat-api.bilibili.co/x/internal/v2/reply/minfo"
    reply_hots = "http://uat-api.bilibili.co/x/internal/v2/reply/hots"

[comment]
    type = 1

[infoc]
    taskID = "001639"
    proto = "tcp"
    addr = "172.18.33.124:15140"
    chanSize = 10240

[search]
    host = "s.search.bilibili.co"

[[notices]]
    noticeType = 1
    showType = 1
    name = "赞"
[[notices]]
    noticeType = 2
    showType = 2
    name = "评论"
[[notices]]
    noticeType = 3
    showType = 3
    name = "粉丝"
[[notices]]
    noticeType = 4
    showType = 4
    name = "系统"

[upload]
    httpschema = "http://"