# This is a TOML document. Boom

version = "1.0.0"
user = "nobody"
pid = "/tmp/notify.pid"
dir = "./"
perf = "0.0.0.0:7630"

[log]
dir = "/data/log/notify"

[bm]
addr = "0.0.0.0:7631"
timeout = "1s"

[clusters]
[clusters.test]
cluster = "test_kafka_9092-266"
brokers = ["172.16.38.154:9192"]
sync = true

[httpClient]
key = "0c4b8fe3ff35a4b6"
secret = "b370880d1aca7d3a289b9b9a7f4d6812"
dial = "500ms"
timeout = "1s"
keepAlive = "60s"
    [httpClient.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[mysql]
	addr = "172.16.33.205"
	dsn = "root@tcp(127.0.0.1:3306)/bilibili_databus_v2?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "1s"
	execTimeout = "1s"
	tranTimeout = "2s"
	[mysql.breaker]
	window = "3s"
	sleep = "100ms"
	bucket = 10
	ratio = 0.5
	request = 100
