# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/up-rating-interface.pid"
dir = "./"
perf = "0.0.0.0:7422"
checkFile = "/data/www/up-rating-interface.html"
family = "up-rating-interface"
address = ""

[bm]
    addr = "0.0.0.0:7420"
    maxListen = 1000
    timeout = "1s"

[log]
    dir = "/data/log/up-rating-interface/"
    stdout = true

[db]
[db.main]
    dsn = "rating:OruSYjDPiZRnsNH860Jl1MEXVgofb9kW@tcp(172.16.33.205:3308)/bilibili_up_rating?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.main.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[db.slave]
    dsn = "rating_reader:tTzLBEk2WRnjKdCuIcbx8XpDr7sy0NH5@tcp(172.16.33.205:3308)/bilibili_up_rating?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.slave.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[multiHTTP]
    [multiHTTP.inner]
    addrs = ["0.0.0.0:7420"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:7421"]
    maxListen = 10

[app]
key = "345b38393c90f093"
secret = "598c2f3e826f36f6feb9c4f671e39adf"

[identify]
    whiteAccessKey = "a2a1eb0ac97d6ba08b85aa0151528f34"
    whiteMid = 23675773
    csrf = true
    [identify.app]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    [identify.memcache]
    name = "go-business/identify"
    proto = "unix"
    addr = "/tmp/shd-platform-identify-web-mc.sock"
    active = 1024
    idle = 64
    dialTimeout = "50ms"
    readTimeout = "90ms"
    writeTimeout = "80ms"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.co"
    secret = "http://open.bilibili.co"
    [identify.httpClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "50ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[redis]
	name = "up-rating-interface"
	proto = "tcp"
	addr = "10.23.103.180:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"
	upRatingExpire = "5m"
