httpToken = "uat"
redisExpire = "30m"
    
[regions]
    "bj" = ["北京","天津","河北","山东","山西","内蒙古","辽宁","吉林","黑龙江","甘肃","宁夏","新疆"]
    "sh" = ["上海","江苏","浙江","安徽","江西","湖北","重庆","陕西","青海","河南","台湾"]
    "gz" = ["广东","福建","广西","海南","湖南","四川","贵州","云南","西藏","香港","澳门"]

[server]
    domain = "broadcast.chat.bilibili.com"
    hostDomain = ".biliapi.com"
    heartbeat = "30s"
	heartbeatMax = 3
    tcpPort = 7821
    wsPort = 7822
    wssPort = 7823
    regionWeight = 1.5

[backoff]
    maxDelay = 120
    baseDelay = 3
    factor = 1.6
    jitter = 0.2

[log]
dir = "/data/log/broadcast-service"
