
tick    = "5m"

interestJSONFile="/data/conf/app-resource/interest.json"
staticJsonFile="/data/conf/static/static.json"

[guideRandom]
    [guideRandom.random]
        iphone = 2
    [guideRandom.buvid]
        iphone = 2

[host]
ad = "http://cm.bilibili.co"
data = "http://172.18.33.162:6193"

[white]
[white.list]
    regex=['^(http(s)?://)?(\w+\.)?(bilibili\.(com|tv|cn)|biligame\.(com|cn)|(bilibiliyoo|im9)\.com|b23\.tv)($|/|\\)']

[ABTest]
Range = 49

[duration]
splash = "2h"

[interestInfoc]
taskID = "001229"
proto = "tcp"
addr = "172.19.100.20:5501"
chanSize = 10240

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "80ms"
timeout   = "500ms"
keepAlive = "60s"
timer = 10
[httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[log]
dir = "/data/log/app-resource/"

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[bm]
    [bm.Outer]
    addr = "0.0.0.0:6851"
    timeout = "1s"

[mysql]
    [mysql.show]
    addr   = "172.16.33.205:3308"
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active = 5
    idle   = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.show.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
    [mysql.resource]
	addr   = "172.16.33.205:3308"
	dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle   = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.resource.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[splash]
[splash.random]
	iphone  = ["250", "249"]
    ipad    = ["255", "254"]
    android = ["275", "274"]

[domain]
    addr = [
        "app.bilibili.com",
        "app.biliapi.net",
        "app.bilapi.com"
    ]