# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/web-show.pid"
dir = "./"
perf = "0.0.0.0:6120"
checkFile = "/data/www/web-show.html"
family = "web-show"
address = "172.16.0.148"

static = "/data/conf/web-show/static"

[Host]
bangumi = "http://bangumi.bilibili.com"
ad = "http://ad.bilibili.co"

[routerconfig]
    [routerconfig.degrade]
        on = false
        args =  ["ids"]

[reload]
jobs ="300s"
notice = "300s"
ad="10s"

[app]
key = "f022126a8a365e20"
secret = "b7b86838145d634b487e67b811b8fab2"

[xlog]
dir = "/data/log/web-show/"
    [xlog.elk]
    project = "web-show"
    addr = "172.18.20.17:8520"
    chanSize = 10240

[statsd]
project = "web-show"
addr = "172.18.20.15:8200"
chanSize = 10240

[httpClient]
dial = "500ms"
timeout = "100ms"
keepAlive = "60s"
key = "f022126a8a365e20"
secret = "b7b86838145d634b487e67b811b8fab2"
timer = 1000
    [httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.1
    request = 10

[multiHTTP]
	[multiHTTP.outer]
	addrs = ["0.0.0.0:6121"]
	maxListen = 100
	[multiHTTP.inner]
	addrs = ["0.0.0.0:6122"]
	maxListen = 10
	[multiHTTP.local]
	addrs = ["0.0.0.0:6123"]
	maxListen = 10

[bm]
	[bm.outer]
	addr = "0.0.0.0:6121"
	maxListen = 100
    timeout = "1s"
	[bm.inner]
	addr = "0.0.0.0:6122"
	maxListen = 10
    timeout = "1s"
	[bm.local]
	addr = "0.0.0.0:6123"
	maxListen = 10
    timeout = "1s"

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "f022126a8a365e20"
    secret = "b7b86838145d634b487e67b811b8fab2"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.httpClient]
    key = "f022126a8a365e20"
    secret = "b7b86838145d634b487e67b811b8fab2"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[rpcClient2]
    [rpcClient2.archive]
        timeout = "30s"
    [rpcClient2.account]
        timeout = "30s"
    [rpcClient2.resource]
        timeout = "30s"      

[mysql]
    [mysql.operation]
    addr = "172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_operation?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.operation.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [mysql.ads]
    addr = "172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_ads?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "800ms"
    [mysql.ads.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [mysql.res]
    addr = "172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.res.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [mysql.cpt]
    addr = "172.16.0.116:3306"
    dsn = "test:test@tcp(172.16.0.116:3306)/bilibili_solar?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.cpt.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[degradeConfig]
    expire = 86400
    [degradeConfig.memcache]
    name = "go-common/app/interface/activity/web-show"
    proto = "tcp"
    addr = "172.16.13.140:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[tracer]
proto = "udp"
addr = "172.16.33.46:5140"
tag = "platform/web-show"
