# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/web-show.pid"
dir = "./"
perf = "0.0.0.0:6120"
checkFile = "/data/www/web-show.html"
family = "web-show"
address = "172.16.0.148"

bangumiuri = "http://bangumi.bilibili.com/api/bp"

[reload]
jobs ="1h"
notice = "300s"
ad="300s"

[app]
key = "f022126a8a365e20"
secret = "b7b86838145d634b487e67b811b8fab2"

[xlog]
dir = "/data/log/web-show/"
    [xlog.elk]
    project = "web-show"
    addr = "172.18.20.17:8520"
    chanSize = 10240

[statsd]
project = "web-show"
addr = "172.18.20.15:8200"
chanSize = 10240

[httpClient]
dial = "500ms"
timeout = "2s"
keepAlive = "60s"
timer = 1000
    [httpClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.1
    request = 100

[multiHTTP]
    [multiHTTP.outer]
    addrs = ["0.0.0.0:6121"]
    maxListen = 10
    [multiHTTP.inner]
    addrs = ["0.0.0.0:6122"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:6123"]
    maxListen = 10

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "6a29f8ed87407c11"
    secret = "d3c5a85f5b895a03735b5d20a273bc57"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[rpcClient2]
    [rpcClient2.archive]
        pullInterval = "10s"
        [rpcClient2.archive.client]
        timeout = "1s"
        timer = 1000
        [[rpcClient2.archive.backup]]
        proto = "tcp"
        addr = "127.0.0.1:6089"
        timeout = "1s"
        timer = 1000
        [rpcClient2.archive.zookeeper]
        root = "/microservice/archive-service/"
        addrs = ["127.0.0.1:2181"]
        timeout = "30s"

[mysql]
[mysql.operation]
    addr = "172.16.0.148:3306"
    dsn = "test:test@tcp(172.16.0.148:3306)/bilibili_operation?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
[mysql.ads]
    addr = "172.16.0.148:3306"
    dsn = "test:test@tcp(172.16.0.148:3306)/bilibili_ads?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
[mysql.res]
    addr = "172.16.0.148:3306"
    dsn = "test:test@tcp(172.16.0.148:3306)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
[mysql.crm]
    addr = "172.16.0.116:3306"
    dsn = "test:test@tcp(172.16.0.116:3306)/bilibili_crm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    
[tracer]
proto = "udp"
addr = "172.16.33.46:5140"
tag = "platform/web-show"
