# This is a TOML document. Boom.
tick = "5m"
MaxAllVsCnt = 4000
MaxAddVsCnt = 100
UgcPayAllowEditDays = 60


[AppEditorInfoc]
taskid = "001729"
proto = "tcp"
addr = "172.18.21.101:5403"
chanSize = 10240

[host]
archive = "http://archive.api.bilibili.co"
www = "http://www.bilibili.com"
member = "http://member.bilibili.com"
apico = "http://api.bilibili.co"
upMng = "http://cm.bilibili.co"
tag = "http://api.bilibili.co"
account = "http://account.bilibili.co"
vdsvc = "http://archive.api.bilibili.co"
elec = "http://elec.bilibili.com"
dynamic = "http://api.vc.bilibili.co"
mainsearch = "http://uat-manager.bilibili.co"
chaodian = "http://chaodian.bilibili.co"

[game]
    OpenHost = "http://line1-game-open-api.biligame.net"
    [game.app]
    key = "EeOpM531WqQnBvu4"
    secret = "gHtKtXTHZJDqGP1tg9ORFs0YWV3kW12V"


[app]
key = "c05dd4e1638a8af0"
secret = "7daa7f8c06cd33c5c3067063c746fdcb"

[httpClient]    
    [httpClient.UpMng]
    key = "test"
    secret = "e6c4c252dc7e3d8a90805eecd7c73396"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.UpMng.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.read]
    key = "c05dd4e1638a8af0"
    secret = "7daa7f8c06cd33c5c3067063c746fdcb"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.read.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.write]
    key = "c05dd4e1638a8af0"
    secret = "7daa7f8c06cd33c5c3067063c746fdcb"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.write.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.fastread]
    key = "c05dd4e1638a8af0"
    secret = "7daa7f8c06cd33c5c3067063c746fdcb"
    dial = "50ms"
    timeout = "100ms"
    keepAlive = "60s"
    timer = 1000
    [httpClient.fastread.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.chaodian]
    key = "chaodian_20190117tangseng"
    secret = "chaodian_20190117tangseng"
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.chaodian.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[memcache]
archiveExpire = "10s"
    [memcache.archive]
    name = "videoup/archive"
    proto = "tcp"
    addr = "172.16.33.54:11213"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [memcache.account]
    name = "videoup/account"
    proto = "tcp"
    addr = "172.16.33.54:11213"
    idle = 5
    active = 10
    dialTimeout = "80ms"
    readTimeout = "200ms"
    writeTimeout = "200ms"
    idleTimeout = "80s"
    submitExpire = "10m"

[redis]
    [redis.videoup]
    name = "videoup"
    proto = "tcp"
    addr = "172.16.33.54:6381"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "10s"

[UpCoverAnti]
    on=true
    second=60
    n=15
    hour=12
    m=1000
[UpCoverAnti.redis]
    name = "videoup/videoup"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    idle = 100
    active = 100
    dialTimeout = "500ms"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    expire = "10m"

[bfs]
Timeout = "2s"
MaxFileSize = 5242880

[bm]
addr = "0.0.0.0:6321"
maxListen = 1000
timeout = "2s"

[limit]
    "AddBasicExp" = "30s"