# This is a TOML document. Boom.

[infoc2]
taskID = "000279"
proto = "tcp"
addr = "172.18.33.125:15140"
chanSize = 10240

[db]
    [db.dmwriter]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmwriter.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmreader]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmreader.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dm]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_dm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "200ms"
    tranTimeout = "200ms"
    [db.dm.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    [redis.dm]
    name = "dm2"
    proto = "tcp"
    addr = "172.18.33.60:6890"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"
    [redis.dmSeg]
    name = "dm2"
    proto = "tcp"
    addr = "172.18.33.60:6890"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"
    [redis.dmRct]
    name = "dm2"
    proto = "tcp"
    addr = "172.18.33.60:6890"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "720h"

[memcache]
    [memcache.dm]
    name = "dm2"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    dmExpire = "24h"
    subjectExpire = "24h"
    ajaxExpire = "1h"
    [memcache.filter]
    name = "filter"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    expire = "1h"
    [memcache.subtitle]
    name = "subtitle"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    expire = "3m"

[localcache]
    oids = [1221,1223]
    expire = "60s"

[httpServer]
    addr = "0.0.0.0:6701"
    maxListen = 1000
    timeout = "1s"

[rpcServer]
discoverOff = false
token = "123456"
[[rpcServer.servers]]
    proto = "tcp"
    addr = "0.0.0.0:6709"
    weight = 10
    group = "test"
[rpcServer.zookeeper]
    root = "/microservice/dm2/"
    addrs = ["172.18.33.172:2181"]
    timeout = "30s"

[host]
    ai = "http://172.16.0.26:8281"
    api = "http://uat-api.bilibili.co"
    archive = "http://archive.api.bilibili.co"
    message = "http://message.bilibili.co"
    search = "http://uat-bili-search.bilibili.co"
    advert = "http://172.16.38.67:8185"
    maskCloud = "http://172.18.33.138:2281/testbucket/"

[httpCli]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpCli.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[archiveRPC]
    group = "test"
    timeout = "3s"

[accountRPC]
    group = "groupapp"
    timeout = "1s"

[assistRPC]
    group="test"
    timeout = "1s"

[coinRPC]
    timeout = "1s"

[seqRPC]
    policy = "sharding"
    timeout = "1s"

[seq]
    [seq.dm]
    businessID = 10
    token      = "Nf9phmDdzjTMW9M5V8YQuLpVTwhvn5IO"
    [seq.subtitle]
    businessID = 11
    token      = "Nf9phmDdzjTMW9M5V8YQuLpVTwhvn5IO"

[locationRPC]
    timeout = "2s"

[relationRPC]
    timeout = "1s"

[thumbupRPC]
    timeout = "100ms"

[supervision]
completed = false
startTime = "2018-05-02 22:15:00"
endTime = "2019-05-05 08:00:00"
location = "中国"

[elastic]
    host = "http://uat-manager.bilibili.co"
    [elastic.httpClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [elastic.httpClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[databus]
    key = "0Pub71UFEMKXu63qtztt"
    secret= "0Pub71UFEMKXu63qtztu"
    group= "DMJob-UGC-P"
    topic= "DMJob-T"
    action="pub"
    name = "dm2"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 5
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[actionpub]
    key = "0Pub71WwEMKXu63qtztu"
    secret= "0Pub71WwEMKXu63qtztv"
    group= "DMAction-UGC-P"
    topic= "DMAction-T"
    action="pub"
    name = "dm2"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 5
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[subtitleCheckPub]
    key = "170e302355453683"
    secret= "51b66df3ebeca2b08f0017f350b6f0ce"
    group= "SubtitleCheck-MainCommunity-P"
    topic= "SubtitleCheck-T"
    action="pub"
    name = "dm2"
    proto = "tcp"
    addr = "172.16.38.154:6205"
    active = 5
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[realname]
    switchOn = false
    whitelist = [10109417,1221]
    [realname.threshold]
    "1,2" = 1010

[antispam]
	on=true
    second=5
    n=10
    hour=1
    m=5
    [antispam.redis]
        name = "dm2/antispam"
        proto = "tcp"
        addr = "172.18.33.60:6890"
        active = 10
        idle = 5
        dialTimeout = "500ms"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"
        expire = "10m"

[bfs]
    host = "http://uat-bfs.bilibili.co"
    timeout = "5s"
    bucket = "test"
    key = "221bce6492eba70f"
    secret = "6eb80603e85842542f9736eb13b7e3"
