version = "1.0.0"
user = "nobody"
pid = "/tmp/manager-admin.pid"
dir = "./"
unameTicker = "1m"

[log]
    dir = "/data/log/manager-admin/"

[HTTPServer]
    addr = "0.0.0.0:6683"
    timeout = "1s"

[httpClient]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "50ms"
    timeout = "3s"

[dsbClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "300ms"
    timeout = "1s"

[orm]
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_manager?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[cfg]
rankGroupMaxPs = 10

[permit]
    [permit.Memcache]
        name = "go-business/auth"
        proto = "tcp"
        addr = "172.18.33.61:11232"
        active = 10
        idle = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"

[memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.18.33.61:11232"
    active = 10
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"