# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/growup-interface.pid"
dir = "./"
perf = "0.0.0.0:7422"
checkFile = "/data/www/growup-interface.html"
family = "growup-interface"
address = ""

[bm]
    addr = "0.0.0.0:7420"
    maxListen = 1000
    timeout = "1s"

[log]
    dir = "/data/log/growup-interface/"
    # [log.agent]
    # family = "growup-interface"
    # taskID = "000057"
    # proto = "unixgram"
    # addr = "/var/run/lancer/collector.sock"
    # chan = 10240

[db]
[db.growup]
    dsn = "growup:test@tcp(172.16.33.205:3307)/bilibili_business_up?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.growup.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[db.allowance]
    dsn = "growup:test@tcp(172.16.33.205:3307)/bilibili_business_up?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [db.allowance.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[multiHTTP]
    [multiHTTP.inner]
    addrs = ["0.0.0.0:7420"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:7421"]
    maxListen = 10

[appConf]
key = "345b38393c90f093"
secret = "598c2f3e826f36f6feb9c4f671e39adf"

[identify]
    whiteAccessKey = "a2a1eb0ac97d6ba08b85aa0151528f34"
    whiteMid = 23675773
    csrf = true
    [identify.app]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    [identify.memcache]
    name = "go-business/identify"
    proto = "unix"
    addr = "/tmp/shd-platform-identify-web-mc.sock"
    active = 1024
    idle = 64
    dialTimeout = "50ms"
    readTimeout = "90ms"
    writeTimeout = "80ms"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.co"
    secret = "http://open.bilibili.co"
    [identify.httpClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "50ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[redis]
    name = "growup-interface"
    proto = "tcp"
    addr = "127.0.0.1:6379"
    idle = 100
    active = 100
    dialTimeout = "500ms"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    expire = "10m"

[httpClient]
    [httpClient.read]
    key = "a4bb50e6f2bc2e0f"
    secret = "test"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.read.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[host]
    archiveURI = "http://uat-api.bilibili.co/x/internal/v2/archive/archives"
    accountURI = "http://uat-api.bilibili.co/x/internal/v3/account/infos"
    uperURI = "http://uat-api.bilibili.co/x/internal/uper/all"
    vipURI = "http://uat-api.bilibili.com/x/internal/big/useBatchInfo"
    activitiesURI = "http://uat-www.bilibili.com/activity/list/"
    relationsURI = "http://api.bilibili.co/x/internal/relation/relations"
    videoUpURI = "http://uat-archive.api.bilibili.co/videoup/view"
    categoriesURI = "http://uat-archive.api.bilibili.co/videoup/types"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "150ms"
readsTimeout = "600ms"
writeTimeout = "200ms"
writesTimeout = "600ms"
    [hbase.zookeeper]
    root = ""
    addrs = ["10.23.58.154:2181","10.23.58.141:2181","10.23.58.20:2181"]
    timeout = "30s"

[threshold]
    limitFanCnt = 3
    limitTotalClick = 500000
    limitArticleView = 1000
