# This is a TOML document. Boom.
[newbie]
    defaultCover = "//i0.hdslb.com/bfs/icon/485664798f87607e76da437903fd6cf2cc15bea3.jpg"
    defaultTalent = "潜力萌新"
    RecommendUpCount = 3
	RecommendUpPoolCount = 10
	ActivityCount = 2
	ActivityShotType = 16
    [newbie.talents]
        24 = "动画新星"
        25 = "动画新星"
        27 = "动画新星"
        47 = "动画新星"

        28 = "唱作新星"
        195 = "唱作新星"

        30 = "灵魂乐手"
        59 = "灵魂乐手"
        196 = "灵魂乐手"

        31 = "实力唱将"

        29 = "音乐鉴赏家"
        54 = "音乐鉴赏家"
        130 = "音乐鉴赏家"

        17 = "头号玩家"
        65 = "头号玩家"
        136 = "头号玩家"
        172 = "头号玩家"
        173 = "头号玩家"

        19 = "格斗新星"

        121 = "潜力导演"
        171 = "电竞达人"

        71 = "综艺大咖"
        131 = "韩圈达人"
        137 = "头号粉丝"

        39 = "博学多才"
        95 = "数码狂人"
        189 = "数码狂人"
        191 = "数码狂人"
        190 = "摄影新星"
        96 = "心系天下"
        98 = "见习机械师"
        122 = "新进技术宅"
        37 = "百科全书"
        124 = "百科全书"
        178 = "百科全书"
        176 = "爱车一族"

        22 = "鬼畜新星"
        26 = "鬼畜新星"
        126 = "鬼畜新星"
        127 = "鬼畜新星"

        20 = "宅舞新星"
        154 = "不如斗舞"
        156 = "不如斗舞"

        157 = "时尚达人"
        158 = "时尚达人"
        159 = "时尚达人"
        164 = "时尚达人"
        193 = "时尚达人"

        21 = "生活达人"
        174 = "生活达人"
        75 = "实习铲屎官"
        76 = "吃货星人"
        138 = "搞笑新星"
        161 = "手工大触"
        162 = "小画家"
        163 = "体育达人"

        166 = "广告达人"

        153 = "国创之光"
        168 = "国创之光"
        169 = "国创之光"

        179 = "资深军迷"
        180 = "乐活达人"

        85 = "影视新星"
        86 = "影视新星"
        182 = "影视新星"
        183 = "影视新星"
        184 = "影视新星"
