# This is a TOML document. Boom.

version = "3.0.0"
user = "nobody"
pid = "/tmp/dynamic-service.pid"
dir = "./"
perf = "127.0.0.1:6239"
checkFile = "/data/www/dynamic.html"
family = "dynamic-service"

bigDataURI = "http://data.bilibili.co"
tickRegion = "5s"
tickTag = "20s"
numArcs = 5
numIndexArcs = 10
minRegionCount = 15

[xlog]
dir = "/data/log/dynamic-service/"


[tracer]
proto = "udp"
addr = "172.16.0.148:5640"
tag = "platform/dynamic-service"

[app]
key = "7c7ac0db1aa05587"
secret = "9a6d62d93290c5f771ad381e9ca23f26"

[httpClient]
    [httpClient.read]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.read.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.write]
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.write.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[multiHTTP]
    [multiHTTP.inner]
    addrs = ["0.0.0.0:6231"]
    maxListen = 1000
    [multiHTTP.local]
    addrs = ["0.0.0.0:6232"]
    maxListen = 100

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "6a29f8ed87407c11"
    secret = "d3c5a85f5b895a03735b5d20a273bc57"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.authHTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.secretHTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100


[rpcServer2]
[[rpcServer2.servers]]
    proto = "tcp"
    addr = ":6235"
    weight = 10
[rpcServer2.zookeeper]
    root = "/microservice/dynamic-service/"
    addrs = ["127.0.0.1:2181"]
    timeout = "1s"

[archiveRPC]
    pullInterval = "10s"
    group = "test"
    [archiveRPC.client]
    token = "123456"
    proto = "tcp"
    addr = "172.16.0.148:6089"
    timeout = "1s"
    timer = 1000
    [archiveRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [archiveRPC.zookeeper]
    root = "/microservice/archive-service/"
    addrs = ["172.16.0.148:2181"]
    timeout = "30s"
