# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
dir = "./"
perf = "0.0.0.0:7290"
family = "passport-service"
env = "qa"

[xlog]
dir = "/data/log/passport-service"

[tracer]
family = "passport-service"
proto = "unixgram"
addr = "/var/run/dapper-collect/dapper-collect.sock"

[switch]
# NOTE: if login log hbase on, default false
loginLogHBase = true
# NOTE: if offer RPC, default false
rpc = false

# NOTE: if switch.rpc = false, ignore rpcServer2 conf.
#[rpcServer2]
#[[rpcServer2.servers]]
#    proto = "tcp"
#    addr = "0.0.0.0:7299"
#    weight = 10
#[rpcServer2.zookeeper]
#    root = "/microservice/passport-service/"
#    addrs = ["172.18.33.172:2181"]
#    timeout = "30s"

[identify]
    WhiteAccessKey = ""
    WhiteMid = 0
    [identify.app]
    key = "e7482d29be4a95b8"
    secret = "test"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.httpClient]
        key = "e7482d29be4a95b8"
        secret = "test"
        dial = "30ms"
        timeout = "100ms"
        keepAlive = "60s"
        [identify.httpClient.breaker]
        window  = "10s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
        [identify.httpClient.url]
        "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
        "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
        "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[hbase]
[hbase.faceApply]
master = ""
meta = ""
testRowKey = "passport-service-ping"
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
[hbase.faceApply.zookeeper]
root = ""
addrs = ["172.18.33.131:2181","172.18.33.168:2181","172.18.33.169:2181"]
timeout = "30s"

[hbase.loginLog]
master = ""
meta = ""
testRowKey = "passport-service-ping"
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
[hbase.loginLog.zookeeper]
root = ""
addrs = ["172.18.33.131:2181","172.18.33.168:2181","172.18.33.169:2181"]
timeout = "30s"

[hbase.pwdLog]
master = ""
meta = ""
testRowKey = "passport-service-ping"
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
[hbase.pwdLog.zookeeper]
root = ""
addrs = ["172.18.33.131:2181","172.18.33.168:2181","172.18.33.169:2181"]
timeout = "30s"