
[log]
    stdout = true

[memcache]
	name = "mcn-interface"
	proto = "tcp"
	addr = "172.16.63.98:11211"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"
    McnSignCacheExpire = "10s"
    McnDataCacheExpire = "30s"

[uploadantispam]
    on=true
    second=60
    n=10
    hour=1
    m=100
    [uploadantispam.redis]
        name = "mcn/mcn-interface"
        proto = "tcp"
        addr = "172.18.33.60:6893"
        idle = 10
        active = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"
        expire = "10m"

[MCNorm]
    dsn = "upcrm:DdL6c5JaWCYKMAQ10PURbfeImow9HXlx@tcp(172.16.33.205:3306)/bilibili_upcrm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 1
    idleTimeout = "4h"


[bfs]
	bucket = "mcn"
	key    = "0i4zga2vht5cnrw6"
	secret = "i3sryb7gdfwvtqmkne49x2ojp8l065"
    # 上传文件大小限制为10M
    maxFileSize = 10485760


[host]
	bfs = "http://uat-bfs.bilibili.co"
	msg = "http://message.bilibili.co"
    Videoup = "http://uat-archive.api.bilibili.co"
    Api     = "http://api.bilibili.co"

[httpClient]
	key = "b8f239ca38a53308"
	secret = "5460ef72fe13c10dfb53442b9111427e"
	dial = "1s"
	timeout = "5s"
	keepAlive = "60s"
	[httpClient.breaker]
		window = "3s"
		sleep = "100ms"
		bucket = 10
		ratio = 0.5
		request = 100

[Other]
    debug = true
    PublicationPriceChangeLimit = "1m"
    WhiteListMid = [370894821, 15555180]

[grpcclient]
    [grpcclient.tag]
	    timeout = "1s"
    [grpcclient.account]
        timeout = "1s"
	[grpcclient.member]
	    timeout = "1s"
	[grpcclient.archive]
	    timeout = "1s"


[RankCache]
    Size = 1024
    ExpireTime = "15s"
    RecommendPoolExpireTime = "15s"

[DataClientConf]
    Key = "b9739fc84d087c4b3c1aa297d01999e6"
    Secret = "5018928e83a23c0cc9773f2571de01e5"


[property]
	    # MCN申请MCN管理入口申请成功
        [[property.msg]]
		    msgType = 1
            code = "116_1_1"
            title = "MCN管理后台申请已通过"
            content = '您申请的mcn管理后台已通过，个人页点击mcn管理中心即可查看，快快去关联旗下up主吧，记得关联上自己的账号哦，点击去#{关联up主}{"https://member.bilibili.com/studio/mcn/m/home"}——”'
		# MCN申请MCN管理入口申请未通过
       [[property.msg]]
			msgType = 2
            code = "116_1_2"
            title = "MCN管理后台申请未通过"
            content = '非常抱歉您的申请由于%s的原因暂未通过，点击#{再次申请}{"https://member.bilibili.com/studio/mcn/m/welcome"}'
		# MCN申请和up主绑定申请授权
       [[property.msg]]
			msgType = 3
            code = "116_2_1"
            title = "MCN账号绑定申请"
            content = '现有用户昵称%s（uid：%d），属于公司%s，申请与您的账号绑定授权。授权后您的账号数据将与对方共享，点击#{查看授权详情}{"https://member.bilibili.com/studio/mcn/authorization/%d?type=bind"}'
		# MCN申请和up主绑定up主同意等待运营审核中                
        [[property.msg]]
			msgType = 4
            code = "116_2_2"
            title = "MCN账号绑定申请"
            content = "您已成功确认与“%s公司”，用户名“%s”，UID：%d的合作关系，我们会在3个工作日内审核并以站内信告知是否绑定。"
		# MCN申请和up主绑定up主同意且运营通过
       [[property.msg]]
			msgType = 5
            code = "116_2_3"
            title = "您已成功与up主账号绑定"
            content = "您已经成功绑定用户昵称%s（uid：%d），您将可以在MCN后台系统中查看该UP主的相关数据"
		# MCN申请和up主绑定up主同意且运营通过
	   [[property.msg]]
			msgType = 6
            code = "116_2_4"
            title = "您已成功与MCN账号绑定"
            content = "您已经成功绑定公司：%s公司，用户名“%s”，UID：%d，您的账号数据将与MCN共享"
		# MCN申请和up主绑定up主同意但运营未通过
       [[property.msg]]
			msgType = 7
            code = "116_2_5"
            title = "您与UP账号绑定审核未通过"
            content = "您与用户昵称%s（uid：%d）的绑定申请，因%s的原因被驳回，绑定失败"
		# MCN申请和up主绑定up主同意但运营未通过
       [[property.msg]]
			msgType = 8
            code = "116_2_6"
            title = "您与MCN账号绑定审核未通过"
            content = "您与%s公司，用户名“%s”，UID：%d，的绑定申请，因%s的原因被驳回，绑定失败"
        # MCN申请和up主绑定被up主拒绝
       [[property.msg]]
			msgType = 9
            code = "116_2_7"
            title = "您与UP账号绑定申请未通过"
            content = "用户昵称%s（uid：%d）拒绝与您的主账号进行绑定，请确认邀请UP主的昵称与UID无误后再次申请"
	    # MCN和up主纠纷处理 - Up主和MCN关系冻结
       [[property.msg]]
			msgType = 10
            code = "116_3_1"
            title = "您与MCN的绑定关系已暂时冻结"
            content = "已暂时冻结您与%s公司，用户名“%s”，UID：%d的合约关系，冻结期内您的所有数据将不再对该账号进行展示"
	    # MCN和up主纠纷处理 - Up主和MCN关系冻结
       [[property.msg]]
			msgType = 11
            code = "116_3_2"
            title = "您与up主的绑定关系已暂时冻结"
            content = "已暂时冻结用户昵称%s（uid：%d）与您的合约关系，冻结期内该UP主的所有数据将不再对您进行展示，此期间该UP的增长数据将不计入您的数据表现中"
		# MCN和up主纠纷处理 - Up主和MCN提前解约
       [[property.msg]]
			msgType = 12
            code = "116_3_3"
            title = "您与MCN的绑定关系已解除"
            content = "已解除您与%s公司，用户名“%s”，UID：%d的合约关系，您的所有数据将不再对该账号进行展示"
		# MCN和up主纠纷处理 - Up主和MCN提前解约
       [[property.msg]]
			msgType = 13
            code = "116_3_4"
            title = "您与up主的绑定关系已解除"
            content = "已解除用户昵称%s（uid：%d）与您的合约关系，该UP主的所有数据将不再对您进行展示，该UP的数据增长将停止在冻结日/解约日"
		# MCN违规账号封禁
       [[property.msg]]
			msgType = 14
            code = "116_4_1"
            title = "MCN后台被暂时封禁"
            content = "非常抱歉您的MCN后台被暂时封禁，冻结期间将无法使用"
		# MCN违规账号清退
       [[property.msg]]
			msgType = 15
            code = "116_4_2"
            title = "MCN后台被关闭"
            content = "非常抱歉您的MCN后台被关闭，关闭后您的MCN后台将无法登录"
		# MCN和B站续约
       [[property.msg]]
		    msgType = 16
            code = "116_1_3"
            title = "MCN管理后台成功续约"
            content = '恭喜您成功续约创作合伙人计划，成为我们新一期的合作伙伴，与我们共同打造良好的站内生态'
		# MCN违规账号冻结期结束，账号恢复
       [[property.msg]]
		    msgType = 17
            code = "116_4_3"
            title = "MCN后台已恢复"
            content = '您的MCN管理后台功能已恢复，点击进入MCN管理后台'
	    # MCN新开权限
       [[property.msg]]
		    msgType = 18
            code = "116_5_1"
            title = "你的%s开通"
            content = '你的%s已开通，快去看看吧——'
	    # MCN权限关闭
       [[property.msg]]
		    msgType = 19
            code = "116_5_2"
            title = "你的%s关闭"
            content = '你的%s被关闭了哦'
	    # UP主不同意授权变更
       [[property.msg]]
		    msgType = 20
            code = "116_6_1"
            title = "与%sUP主的权限变更失败"
            content = '与%sUP主的合作权限变更因up主不同意授权未通过'
	    # 运营不同意授权变更
       [[property.msg]]
		    msgType = 21
            code = "116_6_2"
            title = "与%sUP主的权限变更失败"
            content = '与%sUP主的合作权限变更因%s原因审核未通过'
	    # 运营同意授权变更
       [[property.msg]]
		    msgType = 22
            code = "116_6_3"
            title = "与%sUP主的权限变更成功"
            content = '与%sUP主的合作权限已成功变更，当前权限为：%s'
        # MCN申请与UP主绑定的权限变更
       [[property.msg]]
       		msgType = 23
            code = "116_6_4"
            title = "您与%sMCN的授权发生变更，请确认是否同意"
            content = '%sMCN申请与您的权限变更为：%s，#{点击链接}{"https://member.bilibili.com/studio/mcn/authorization/%d?type=reauth"}确认是否同意变更权限'