# This is a TOML document. Boom.

tick = "5m"
maxAssCnt = 10
maxTypeCnt = 100

[host]
api = "http://api.bilibili.com"
member = "http://member.bilibili.com"
account = "http://account.bilibili.com"
message = "http://message.bilibili.com"

[xlog]
dir = "/data/log/assist-service/"
    [xlog.elk]
    project = "assist-service"
    addr = "172.18.20.17:8520"
    chanSize = 1024

[app]
key = "b8f239ca38a53308"
secret = "5460ef72fe13c10dfb53442b9111427e"

[relationSub]
key = "0QEO9F8JuuIxZzNDvklH"
secret = "0QEO9F8JuuIxZzNDvklI"
group = "Relation-Assist-S"
topic = "Relation-T"
action = "sub"
offset = "old"
buffer = 128
name = "assist-service/relation-sub"
proto = "tcp"
addr = "172.16.33.158:6205"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[httpClient]
    [httpClient.normal]
    key = "b8f239ca38a53308"
    secret = "5460ef72fe13c10dfb53442b9111427e"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
    [httpClient.normal.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.slow]
    key = "b8f239ca38a53308"
    secret = "5460ef72fe13c10dfb53442b9111427e"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 10
   [httpClient.slow.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[bm]
	[bm.inner]
    addr = "0.0.0.0:6721"
    maxListen = 1000
    timeout = "2s"
    [bm.local]
    addr = "0.0.0.0:6722"
    maxListen = 1000
    timeout = "1s"

[rpcServer2]
  discoverOff = false
  token = "123456"
[[rpcServer2.servers]]
    proto = "tcp"
    addr = "0.0.0.0:6729"
    weight = 10
    group = "uat"
[rpcServer2.zookeeper]
    root = "/microservice/assist-service/"
    addrs = ["172.18.33.50:2199","172.18.33.51:2199","172.18.33.52:2199"]
    timeout = "30s"

[db]
    [db.assist]
    name = "[archive]tcp@172.16.33.54:3306"
    dsn = "test:test@tcp(172.16.33.54:3306)/bilibili_assist?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [db.assist.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[memcache]
    [memcache.assist]
    name = "assist-service"
    proto = "tcp"
    addr = "172.16.33.54:11212"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[redis]
    [redis.assist]
    name = "assist/assist"
    proto = "tcp"
    addr = "172.16.33.54:6381"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"