[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "b1014d7c339a5649"
    secret = "75b74b612aa792b112e6504cae44c319"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.httpClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "30ms"
    timeout = "150ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  ="10s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[log]
    dir = "/data/log/playlist/"

[app]
    key = "b1014d7c339a5649"
    secret = "75b74b612aa792b112e6504cae44c319"

[HTTPServer]
    addr = "0.0.0.0:7151"
    timeout = "1s"

[rpcServer2]
[[rpcServer2.servers]]
    proto = "tcp"
    addr = ":7159"
    weight = 10
[rpcServer2.zookeeper]
    root = "/microservice/playlist-service/"
    addrs = ["172.18.33.172:2181"]
    timeout = "60s"

[viewDatabus]
    key = "9765cdac5894f2ba"
    secret= "1448f5f2cd6029f6af6c5d438cd31edd"
    group= "StatView-MainWebSvr-P"
    topic= "StatView-T"
    action="pub"
    name = "playlist/playlist-pub/view"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"


[shareDatabus]
    key = "9765cdac5894f2ba"
    secret= "1448f5f2cd6029f6af6c5d438cd31edd"
    group= "StatShare-MainWebSvr-P"
    topic= "StatShare-T"
    action="pub"
    name = "playlist/playlist-pub/share"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

    
[favoriteRPC]
    timeout = "1s"

[archiveRPC]
    timeout = "1s"

[accountRPC]
    timeout = "200ms"

[filterRPC]
    timeout = "1s"

[mysql]
    addr = "172.16.33.205"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_playlist?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout = "4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    name = "playlist"
    proto = "tcp"
    addr = "172.18.33.60:6894"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    statExpire = "24h"
    plExpire = "24h"

[httpClient]
    key = "b1014d7c339a5649"
    secret = "75b74b612aa792b112e6504cae44c319"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"

[rule]
    maxNameLimit = 80
    maxPlDescLimit = 250
    maxVideoDescLimit = 80
    maxArcChangeLimit = 100
    maxVideoCnt = 100
    maxPlCnt = 100
    maxPlsPageSize = 30
    maxPlArcsPs = 100
    sortStep = 100
    minSort = 0
    beginSort = 1000
    maxSearchArcPs = 30
    maxSearchLimit = 30
    powerMids = [101, 27515235, 2089809, 27515232]

[host]
    search = "http://s.search.bilibili.co"