# This is a TOML document. Boom

version = "1.0.0"
user = "nobody"
pid = "/tmp/upload.pid"
dir = "./"

bfsDownloadHost = "uat-i0.hdslb.com"
bfsUpdateHost = "uat-bfs.bilibili.co"
bfsDeleteHost = "uat-bfs.bilibili.co"

[bm]
	addr = "0.0.0.0:9001"
	maxListen = 10
	timeout = "1s"

[multiHTTP]
	[multiHTTP.outer]
	addrs = ["0.0.0.0:6121"]
	maxListen = 10
	[multiHTTP.inner]
	addrs = ["0.0.0.0:6122"]
	maxListen = 10
	[multiHTTP.local]
	addrs = ["0.0.0.0:6123"]
	maxListen = 10

[identify]
	whiteAccessKey = ""
	whiteMid = 0
	[identify.app]
	key = "6a29f8ed87407c11"
	secret = "d3c5a85f5b895a03735b5d20a273bc57"
	[identify.memcache]
	name = "go-business/identify"
	proto = "tcp"
	addr = "172.16.33.54:11211"
	active = 10
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "80s"
	[identify.host]
	auth = "http://uat-passport.bilibili.co"
	secret = "http://uat-open.bilibili.co"
	[identify.httpClient]
	key = "f022126a8a365e20"
	secret = "b7b86838145d634b487e67b811b8fab2"
	dial = "30ms"
	timeout = "100ms"
	keepAlive = "60s"
	[identify.httpClient.breaker]
	window  = "10s"
	sleep   = "100ms"
	bucket  = 10
	ratio   = 0.5
	request = 100
	[identify.httpClient.url]
	"http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
	"http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
	"http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[orm]
    dsn = "test:test@tcp(172.16.33.205:3308)/bfs?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 10
    idleTimeout = "4h"

[httpClient]
   [httpClient.read]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "50ms"
    timeout = "500ms"
    keepAlive = "60s"
    timer = 16
    [httpClient.read.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [httpClient.write]
    key = "6aa4286456d16b97"
    secret = "351cf022e1ae8296109c3c524faafcc8"
    dial = "50ms"
    timeout = "800ms"
    keepAlive = "60s"
    timer = 16
    [httpClient.write.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 10
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[bfs]
BfsUrl = "uat-bfs.bilibili.co"
WaterMarkUrl = "http://172.18.33.121:8090/imageserver/watermark/gen"
ImageGenURL = "http://172.18.33.121:8090/imageserver/image/gen"
TimeOut = "10s"


[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
    [hbase.zookeeper]
    root = ""
     addrs = ["172.18.33.131:2181","172.18.33.168:2181","172.18.33.169:2181"]
    timeout = "30s"