version = "1.0.0"
user = "nobody"
pid = "/tmp/card-admin.pid"
dir = "./"
unameTicker = "1m"

[bm]
	addr = "0.0.0.0:7891"
	maxListen = 1000
	timeout = "1s"

[orm]
    dsn = "root:123456@tcp(127.0.0.1:3306)/bilibili_card?timeout=3s&readTimeout=3s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[memcache]
	name = "card-service"
	proto = "tcp"
	addr = "172.18.33.60:11233"
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[permit]
    [permit.Memcache]
        name = "go-business/auth"
        proto = "tcp"
        addr = "172.18.33.61:11232"
        active = 10
        idle = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"

[bfs]
    key = "b2f31180234e497c"
    secret = "e96a241fb05f449502420d9271b2ed"
    host = "http://uat-bfs.bilibili.co"
    timeout = 1000
    maxFileSize = 5242880