# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/growup-admin.pid"
dir = "./"
perf = "0.0.0.0:7412"
checkFile = "/data/www/growup-admin.html"
family = "growup-admin"
address = ""

[log]
    dir = "/data/log/growup-admin/"
    stdout = true
    # [log.agent]
    # family = "growup-admin"
    # taskID = "000057"
    # proto = "unixgram"
    # addr = "/var/run/lancer/collector.sock"
    # chan = 10240

[app]
    key = "c1a1cb2d89c33794"
    secret = "dda47eeca111e03e6845017505baea13"

[orm]
[orm.growup]
	dsn = "growup:test@tcp(172.16.33.205:3307)/bilibili_business_up?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle = 5
	idleTimeout = "4h"
[orm.allowance]
	dsn = "growup:test@tcp(172.16.33.205:3307)/bilibili_business_up?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "10s"
    [orm.allowance.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[host]
    message = "https://message.bilibili.co"
    videoType = "http://uat-archive.api.bilibili.co"
    columnType = "https://api.bilibili.com"
    creative = "http://api.bilibili.co"
    api = "http://api.bilibili.co"

[bfs]
addr        = "http://uat-bfs.bilibili.co"
bucket      = "test"
key         = "221bce6492eba70f"
secret      = "6eb80603e85842542f9736eb13b7e3"
# 上传文件大小限制为1M
maxFileSize = 1048576

[httpClient]
key = "c1a1cb2d89c33794"
secret = "dda47eeca111e03e6845017505baea13"
dial = "2s"
timeout = "3s"
keepAlive = "60s"
timer = 10
[httpClient.breaker]
window = "10s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request =  100

[bm]
	addr = "0.0.0.0:7410"
	maxListen = 10
	timeout = "10s"

[budget]
[budget.video]
    year = 2018
    annualBudget = 130000000
    dayBudget = 350000
[budget.column]
    year = 2018
    annualBudget = 5000000
    dayBudget = 13500
[budget.bgm]
    year = 2018
    annualBudget = 5000000
    dayBudget = 13500

[ShellConf]
    CustomId = "10014"
    Token = "375a597cf22a6fb5d6f821446a1313be"
    PayHost = "pay.bilibili.co"
    CallbackUrl = "http://api.bilibili.co/x/internal/growup/offlineactivity/callback"

[OtherConf]
    OfflineOrderConsume = false