[mysql]
	addr = "127.0.0.1:3306"
	dsn = "test:test@tcp(127.0.0.1:3306)/bilibili_ugcpay?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["test:test@tcp(127.0.0.1:3306)/bilibili_ugcpay?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"

[memcache]
	name = "ugcpay"
	proto = "tcp"
	addr = ""
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	active = 50
	idle = 10
	idleTimeout = "10s"

[redis]
	name = "ugcpay"
	proto = "tcp"
	addr = ""
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	active = 50
	idle = 10
	idleTimeout = "10s"

[cacheTTL]
	OrderTTL                 = 1800
	AssetTTL                 = 64800
	AssetRelationTTL         = 7200
	AggrIncomeUserTTL        = 7200
	AggrIncomeUserMonthlyTTL = 7200

[biz]
	RunCASTimes = 3
	[biz.pay]
		Token = "310f84dcc88ec8a0a9247f3b75b93614"
		ID = "10017"
		OrderTTL = 1800
		URLQuery  = "http://pay.bilibili.com/payplatform/pay/query"
		URLCancel = "http://pay.bilibili.co/payplatform/pay/cancel"
		URLPayCallback = "http://api.bilibili.co/x/internal/ugcpay/trade/pay/callback"
		URLRefund = "http://pay.bilibili.co/payplatform/refund/request"
		URLRefundCallback = "http://api.bilibili.co/x/internal/ugcpay/trade/pay/refund/callback"
	[biz.price]
		[biz.price.PlatformTax]
			ios = 1.3
