# This is a TOML document. Boom.

version = "1.1.0"
user    = "nobody"
pid     = "/tmp/app-show.pid"
dir     = "./"
perf    = "127.0.0.1:6100"
checkFile = "/data/www/app-show.html"
family = "app-show"
address = ""
trace   = true
debug   = false

env     = "test"
tick    = "10m"

[duration]
splash = "2h"
search = "-504h"

[infoc]
path = ""
project = "app-show"
name = "app-show"

[infoc2]
taskID = "000026"
proto = "tcp"
addr = ""
chanSize = 10240

[feedinfoc2]
taskID = "0000236"
proto = "tcp"
addr = ""
chanSize = 10240

[json]
staticDir = "/app-show-static/"

[host]
live      = "http://live.bilibili.com"
bangumi   = "http://bangumi.bilibili.com"
hetongzi  = "http://data-test.bilibili.co"
data      = "http://data-test.bilibili.co"
mipush    = "https://api.xmpush.xiaomi.com"
apiCo     = "http://api.bilibili.co"
apiCoX    = "http://api.bilibili.co"
www       = "http://www.bilibili.com"
ad        = "http://ad.bilibili.co"
search    = "http://s.search.bilibili.co"
activity  = "http://matsuri.bilibili.co"
apiLiveCo =  "http://api.live.bilibili.co"
# ad      = "http://172.16.33.180:8082"

[tracer]
    family = "app-show"
    proto = "unixgram"
    addr = "/var/run/dapper-collect/dapper-collect.sock"

[xlog]
dir = "/data/log/app-show/"
	[xlog.elk]
	project  = "app-show"
	addr     = "172.18.20.17:8520"
	chanSize = 10240

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer = 10
[httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpClientAsyn]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "1s"
timeout   = "2s"
keepAlive = "60s"
timer = 10
[httpClientAsyn.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpData]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer     = 10
[httpData.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.httpClient]
	key = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[multiHttp]
	[multiHttp.outer]
	addrs     = ["0.0.0.0:6101"]
	maxListen = 100
	[multiHttp.inner]
	addrs     = ["0.0.0.0:6102"]
	maxListen = 100
	[multiHttp.local]
	addrs     = ["0.0.0.0:6103"]
	maxListen = 100

[archiveRPC]
	group = "test"
    pullInterval = "10s"
    [archiveRPC.client]
    proto = "tcp"
    timeout = "1s"
    timer = 1000
	token = "123456"
	[archiveRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [archiveRPC.zookeeper]
    root = "/microservice/archive-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[dynamicRPC]
    pullInterval = "10s"
    [dynamicRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6239"
    timeout = "1s"
    timer = 1000
    [dynamicRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [dynamicRPC.zookeeper]
    root = "/microservice/dynamic-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[accountRPC]
    pullInterval = "10s"
    [accountRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6079"
    timeout = "1s"
    timer = 1000
    [accountRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [accountRPC.zookeeper]
    root = "/microservice/account-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[relationRPC]
    pullInterval = "10s"
    [relationRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6079"
    timeout = "1s"
    timer = 1000
    [relationRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [relationRPC.zookeeper]
    root = "/microservice/relation-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[resourceRPC]
    pullInterval = "10s"
    [resourceRPC.client]
    proto = "tcp"
    addr = "172.16.33.56:6079"
    timeout = "1s"
    timer = 1000
	[resourceRPC.client.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [resourceRPC.zookeeper]
    root = "/microservice/article-service/"
    addrs = ["172.16.33.54:2181"]
    timeout = "30s"

[mysql]
	[mysql.show]
	addr   = "172.16.33.205:3308"
	dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle   = 2
	idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.show.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
	[mysql.resource]
	addr   = "172.16.33.205:3308"
	dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle   = 2
	idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.resource.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[redis]
	[redis.recommend]
	name   = "app-show/recommend"
	proto  = "tcp"
	addr   = "172.16.33.54:6380"
	active = 20
	idle   = 10
	dialTimeout  = "50ms"
	readTimeout  = "100ms"
	writeTimeout = "100ms"
	idleTimeout  = "80s"
	expire = "2h"
	[redis.stat]
	name   = "app-interface/stat"
	proto  = "tcp"
	addr   = "172.16.33.54:6380"
	active = 20
	idle   = 10
	dialTimeout  = "50ms"
	readTimeout  = "50ms"
	writeTimeout = "50ms"
	idleTimeout  = "80s"
	expire = "10s"

[memcache]
	[memcache.archive]
	name   = "app-show/archive"
	proto  = "tcp"
	addr   = "172.16.33.54:11213"
	active = 50
	idle   = 10
	dialTimeout  = "50ms"
	readTimeout  = "100ms"
	writeTimeout = "100ms"
	idleTimeout  = "80s"
	expire = "2h"

[dislikeDatabus]
		key = "0PtMsVFzWyyvoTgAyLCG"
		secret= "0PtMsVFzWyyvoTgAyLCH"
		group= "TagDislike-SkyHorse-P"
		topic= "Dislike-T"
		action="pub"
		[dislikeDatabus.redis]
		name = "app-feed/dislike"
		proto = "tcp"
		addr = "172.16.33.56:6205"
		active = 100
		idle = 50
		dialTimeout = "50ms"
		readTimeout = "200ms"
		writeTimeout = "200ms"
		idleTimeout = "80s"

[recommend]
[recommend.host]
	1 = ["172.16.33.62"]
[recommend.group]
	0  = 1
	1  = 1
	2  = 1
	3  = 1
	4  = 1
	5  = 1
	6  = 1
	7  = 1
	8  = 1
	9  = 1
	10 = 1
	11 = 1
	12 = 1
	13 = 1
	14 = 1
	15 = 1
	16 = 1
	17 = 1
	18 = 1
	19 = 1
