[host]
search = "http://uat-manager.bilibili.co/"

[XLog]
stdout=true

[infoc]
    taskID = "000308"
    proto = "tcp"
    addr = "172.19.100.20:5401"
    chanSize = 10240

[bm]
    addr = "0.0.0.0:9000"
    timeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"

[seq]
    businessID = 6
    token      = "RA8yy0RjDCBTGgFUha4hPOnhxfXvM8hR"

[appkeytype]
"c1a1cb2d89c33794" = [1]      # 稿件
"53e2fa226f5ad348" = [1]        # 稿件
"33ac033ce123e590" = [4,9]   # 活动,活动稿件
"1320e897e00d4c1c" = [5]      # 直播小视频、直播文章
"903f486ae7dc87fa" = [6,7,15]   # 封禁信息、风纪委
"90e40332a3d3ba15" = [7]     # 公告信息
"58344a540b61aebf" = [8,10] # 直播活动、直播公告
"9edfa647fbfde3e2" = [11]      # 有文画站
"9cfc54570033cd61" = [12]    # 文章
"7d9f6f6fe2a898e8" = [13]      #  票务
"0c4b8fe3ff35a4b6" = [14,19]   # 音乐、音乐播单
"27773a832a67e55f" = [16,20,21]      # 点评、漫画部评论、漫画话评论
"fb06a25c6338edbc" = [17]      #庐山动态
"b1014d7c339a5649" = [18]     # 播单

[identify]
    whiteAccessKey = "nKUPGzuhU|vTG58H!HPKLlktz{8}3^"
    whiteMid = 88889082
    csrf = true
    [identify.app]
    key = "c1a1cb2d89c33794"
    secret = "dda47eeca111e03e6845017505baea13"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.co"
    secret = "http://open.bilibili.co"
    [identify.httpClient]
    key = "c1a1cb2d89c33794"
    secret = "dda47eeca111e03e6845017505baea13"
    dial = "30ms"
    timeout = "100ms"
    keepAlive = "60s"
    [identify.httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.httpClient.url]
    "http://passport.bilibili.co/intranet/auth/tokenInfo" = {timeout = "100ms"}
    "http://passport.bilibili.co/intranet/auth/cookieInfo" = {timeout = "100ms"}
    "http://open.bilibili.co/api/getsecret" = {timeout = "500ms"}

[reply]
    maxPageSize = 20
    minConLen = 2
    maxConLen = 1000
    secondDefSize = 5
    secondDefPageNum = 1
    maxEmoji = 20
    emojiExpire = "1m"
    aitopicurl = "http://172.22.33.111:8100/topicrec"
    bigdataurl = "http://172.18.18.11:8888/comment"
    filter ="http://uat-api.bilibili.co"
    vipUrl ="http://uat-vip.bilibili.co"
    fansreceivedlisturl = "http://uat-api.live.bilibili.co/fans_medal/v1/fans_medal/get_list_weared"
    captchaTokenURL = "http://api.bilibili.co/x/internal/v1/captcha/token"
    captchaVerifyURL = "http://api.bilibili.co/x/internal/v1/captcha/verify"
    blockstatusurl="http://uat-account.bilibili.co/api/member/getBlockAndMoralStatus"
    credituserurl = "http://uat-blocked.bilibili.co/internal/v1/jury/info"
    forbidList = [11191454,9685876]
    [reply.SortByHotOids]
    "10100715"=1
    [reply.BnjAidHotNum]
    "10098208"=10
    [reply.HotReplyConfig]
    "1" = {"10098208" = 10}

[httpClient]
    key = "c1a1cb2d89c33794"
    secret = "dda47eeca111e03e6845017505baea13"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[drawyooHTTPClient]
    key = "49df034922d68827"
    secret = "92ce984f5c8b8415366838c6ee3e039f"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [drawyooHTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.1
    request = 100

[mysql]
    [mysql.reply]
    addr= "172.22.34.101:3306"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_reply?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "200ms"
    tranTimeout = "200ms"
    [mysql.reply.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [mysql.replySlave]
    addr= "172.22.34.101:3306"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_reply?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [mysql.replySlave.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
[supervision]
startTime = "2017-06-02 22:15:00"
endTime = "2017-06-05 08:00:00"
completed = false
location = "中国"

[assistConfig]
startTime = "2017-07-11 22:15:00"

[identification]
switchon = true

[databus]
key = "170e302355453683"
secret = "3d0e8db7bed0503949e545a469789279"
group = "ReplyAdd-MainCommunity-P"
topic = "ReplyAdd-T"
action ="pub"
name = "reply/interface"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 2
active = 5
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "1h"
[databus.discovery]
    domain = "api.bilibili.co"
    key = "0c4b8fe3ff35a4b6"
    secret = "b370880d1aca7d3a289b9b9a7f4d6812"

[memcache]
proto = "tcp"
addr = "172.18.33.61:11213"
idle = 10
active = 10
dialTimeout = "2s"
readTimeout = "2s"
writeTimeout = "2s"
idleTimeout = "7h"
expire = "24h"

[redis]
proto = "tcp"
addr = "172.18.33.60:6889"
idle = 10
active = 10
dialTimeout = "500ms"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"
indexExpire = "24h"
reportExpire = "24h"
userCntExpire = "30s"
userActExpire= "1h"
notifyExpire= "24h"

[rpcClient2]
    [rpcClient2.account]
        timeout = "1s"
        color = "blueandred"
    [rpcClient2.filter]
        timeout = "1s"
    [rpcClient2.location]
        timeout = "1s"
    [rpcClient2.assist]
        timeout = "1s"
    [rpcClient2.figure]
        timeout = "1s"
	[rpcClient2.seq]
	    timeout = "1s"
    [rpcClient2.thumbup]
	    timeout = "1s"
