
[mysql]
	addr = "127.0.0.1:3306"
	dsn = "test:test@tcp(127.0.0.1:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["test:test@tcp(127.0.0.2:3306)/test? timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4","test:test@tcp(127.0.0.3:3306)/test?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "100ms"
	execTimeout = "100ms"
	tranTimeout = "200ms"

[redis]
	name = "xanchor-service"
	proto = "tcp"
	addr = ""
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[memcache]
	name = "xanchor-service"
	proto = "tcp"
	addr = ""
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[liveDanmuSub]
    key = "ec4c0820d525d67b"
    secret = "e20f8f664bf10722efeb6aac0cc16011"
    group = "LiveXanchor-LiveLive-S"
    topic = "LiveDanmuSend-T"
    action ="sub"
    name = "service/xacnhor"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 10
    active = 100
    dialTimeout = "10s"
    readTimeout = "40s"
    writeTimeout = "10s"
    idleTimeout = "60s"
[liveGiftSendSub]
      key = "ec4c0820d525d67b"
      secret = "e20f8f664bf10722efeb6aac0cc16011"
      group = "LiveXanchor-LiveLive-S"
      topic = "LiveGiftSend-T"
      action ="sub"
      name = "service/xacnhor"
      proto = "tcp"
      addr = "172.18.33.50:6205"
      idle = 10
      active = 100
      dialTimeout = "10s"
      readTimeout = "40s"
      writeTimeout = "10s"
      idleTimeout = "60s"