# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
dir = "./"
perf = "0.0.0.0:7270"
family = "usersuit-admin"
env = "qa"

[xlog]
    dir = "/data/log/usersuit-admin"

[tracer]
    family = "usersuit-admin"
    proto = "unixgram"
    addr = "/var/run/dapper-collect/dapper-collect.sock"

[bm]
	[bm.inner]
	addr = "0.0.0.0:7271"
	maxListen = 1000
    timeout = "1s"

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://uat-dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.18.33.61:11219"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[accountRPC]
    timeout = "1s"

[db]
    [db.usersuit]
    addr = "172.16.33.205:3309"
    dsn = "usersuit:cDXL6vncmCQanx4iMgGogu6gYz33NmA1@tcp(172.16.33.205:3309)/usersuit?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN = ["usersuit:cDXL6vncmCQanx4iMgGogu6gYz33NmA1@tcp(172.16.33.205:3309)/usersuit?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
    active = 5
    idle = 2
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [db.usersuit.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[host]
    bfs = "http://uat-bfs.bilibili.co"
    #bfs = "http://bfs.bilibili.co"
    manager = "http://manager.bilibili.co"
    msg = "http://message.bilibili.co"
    passport = "http://passport.bilibili.co"

[bfs]
bucket = "face"
key    = "792d70f16e958493"
secret = "08525fe929bdb26c3a6009afd7318f"


[httpClient]
    key = "837f620f5c0a8010"
    secret = "2a9057021014b4b843b635664c69d5df"
    dial = "500ms"
    timeout = "1s"
    keepAlive = "60s"
    [httpClient.breaker]
        window  = "3s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
    
[redis]
    name = "usersuit"
    proto = "tcp"
    addr = "127.0.0.1:6379"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[accountNotify]
    key = "4ba46ba31f9a44ef"
    secret = "99985eb4451cfb1b899ca0fbe3c4bdc8"
    group = "AccountNotify-MainAccount-P"
    topic = "AccountNotify-T"
    action = "pub"
    offset = "old"
    buffer = 128
    name = "usersuit-admin/databus"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

    [memcache]
    name = "usersuit-service"
    proto = "tcp"
    addr = "172.18.33.61:11219"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "24h"
    pointexpire = "168h"


    [ecode]
    domain = "172.16.33.248:6401"
    all = "1h"
    diff = "10m"
    [ecode.clientconfig]
        key = "test"
        secret = "e6c4c252dc7e3d8a90805eecd7c73396"
        dial      = "2s"
        timeout   = "2s"
        keepAlive = "10s"
        [ecode.clientconfig.breaker]
            window  ="3s"
            sleep   ="100ms"
            bucket  = 10
            ratio   = 0.5
            request = 100
    [ecode.app]
         key = "test"
         secret = "e6c4c252dc7e3d8a90805eecd7c73396"