# This is a TOML document. Boom

env = "uat"
sourcePath = "/Users/caocao/Code/go/src/go-common/app/admin/openplatform/sug/source/"

[url]
itemSearch = "http://fat1-mall.bilibili.co/mall-items/items/itemsListByQuery"

[auth]
    managerHost = "http://manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"


[redis]
    name = "sug-season"
    proto = "tcp"
    addr = "172.16.33.203:6379"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "1m"


[httpClient]
    key = "ad4bb9b8f5d9d4a7"
    secret = "6912080d78d58be7cb94f57d50d438f6"
    dial = "1s"
    timeout = "10s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
        window  = "10s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[es]
    addr = ["http://172.16.38.126:9201"]

[db]
    [db.mallDB]
        addr = "172.22.34.101:3310"
        dsn ="mall:FIb1lia9lK4UufUScJjrxvbkrEZtZD4l@tcp(172.22.34.101:3310)/open_mall?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4" 
        active = 5
        idle = 5
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "2s"
    [db.mallDB.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

     [db.ticketDB]
              addr = "172.22.34.101:3310"
              dsn = "ticket:i9HXWAvzWiqPxMxlfsQ8DRqYydjf3pYa@tcp(172.22.34.101:3310)/open_ticket?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
              active = 5
              idle = 5
              queryTimeout = "1s"
              execTimeout = "1s"
              tranTimeout = "2s"
          [db.ticketDB.breaker]
              window = "3s"
              sleep = "100ms"
              bucket = 10
              ratio = 0.5
              request = 100

[bfs]
    timeout = "2s"
    maxFileSize = 5242880
    key = "c387398b08495933"
    secret = "18295608cd3b8a5lbbe2b07a509705"
    addr = "http://bfs.bilibili.co/bfs/openplatform/"
    bucket = "openplatform"

