# This is a TOML config file.

[httpClient]
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[httpFigure]
    infoURL = "http://uat-api.bilibili.co/x/internal/figure/info"
    key = "89ffc6e896106fd3"
    secret = "1359cdbaf9ff6e2f9b6251579d966101"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [httpFigure.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100


[HTTPServer]
    addr = "0.0.0.0:6214"
    maxListen = 1000
    timeout = "1s"
    readTimeout = "800ms"
    writeTimeout = "800ms"

[host]
    api = "http://uat-api.bilibili.co"
    archive = "http://uat-archive.api.bilibili.co"
    message = "http://message.bilibili.co"

[db]
    [db.dm]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_dm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "200ms"
    tranTimeout = "200ms"
    [db.dm.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmMetaReader]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmMetaReader.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100
    [db.dmwriter]
    addr = "172.16.33.205:3310"
    dsn = "test_3308:test_3308@tcp(172.16.33.205:3310)/bilibili_dm_meta?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [db.dmwriter.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    [redis.dm]
    name = "dm/dm"
    proto = "tcp"
    addr = "172.16.33.54:6379"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    dmidExpire = "1h"
    indexExpire = "1h"
    lockExpire = "10s"
    videoExpire = "1h"

[archiveRPC]
    group = "uat"
    timeout = "1s"

[accountRPC]
    group = "v7"
    timeout = "1s"

[assistRPC]
    group="uat"
    timeout = "1s"

[dmRPC]
    timeout = "1s"

[dmReport]
    count = 3
    mcKey = "1_6_5"
    msgURL = "http://message.bilibili.com/api/notify/send.user.notify.do"

[databus]
    key = "170e302355453683"
    secret = "51b66df3ebeca2b08f0017f350b6f0ce"
    group = "DMReport-MainCommunity-P"
    topic = "DMReport-T"
    action = "pub"
    name = "dm"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[antispam]
	on=true
    second=4
    n=1
    hour=12
    m=1000
    [antispam.redis]
        name = "dm/dm"
        proto = "tcp"
        addr = "172.16.33.54:6379"
        idle = 5
        active = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"

[es]
    host="http://uat-manager.bilibili.co"
    [es.httpClient]
    key="3c4e41f926e51656"
    secret="26a2095b60c24154521d24ae62b885bb"
    timeout = "8s"
    dial = "1s"

