# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
dir = "./"
perf = "0.0.0.0:6330"
family = "relation-job"
env = "test"

[xlog]
dir = "/data/log/relation-job"

[multiHTTP]
	[multiHTTP.inner]
	addrs = ["0.0.0.0:6331"]
	maxListen = 1000

[mysql]
addr = "172.16.33.101:3306"
dsn = "account:wx2U1MwXRyWEuURw@tcp(172.16.33.101:3306)/relation?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2
idleTimeout ="4h"
queryTimeout = "100ms"
execTimeout = "100ms"
tranTimeout = "200ms"
[mysql.breaker]
window = "3s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100

[memcache]
name = "relation-job"
proto = "tcp"
addr = "192.168.99.100:32777"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "24h"

[redis]
name = "go-common/app/job/main/relation"
proto = "tcp"
addr = "127.0.0.1:32769"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "720h"

[relRedis]
name = "relation-service"
proto = "tcp"
addr = "127.0.0.1:32769"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "720h"

[clearPath]
following = "http://api.bilibili.co/x/internal/relation/cache/following/update"
follower = "http://api.bilibili.co/x/internal/relation/cache/follower/del"
stat = "http://api.bilibili.co/x/internal/relation/cache/stat/del"

[apiPath]
followersNotify = "http://message.bilibili.co/api/notify/send.user.notify.do"

[httpClient]
    key = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
dial      = "100ms"
timeout   = "1s"
keepAlive = "60s"
timer     = 128
    [httpClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    
[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[databus]
key = "0QBAaL5f8hupBjLQydZt"
secret = "0QBAaL5f8hupBjLQydZu"
group = "Relation-Friends-S"
topic = "Relation-T"
action = "sub"
offset = "old"
buffer = 2048
name = "go-common/app/job/main/relation/databus"
proto = "tcp"
addr = "172.16.33.158:6205"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[sms]
phone="15121003430,13601914616"
token="460d52f1-dafe-44a2-911a-9f308968309a"

[relation]
followersUnread = "1m"