version = "1.0.0"
user = "nobody"
pid = "/tmp/open-admin.pid"
dir = "./"
unameTicker = "1m"

[log]
    dir = "/data/log/open-admin/"

[permit]
    [permit.Memcache]
        name = "go-business/auth"
        proto = "tcp"
        addr = "172.16.33.54:11211"
        active = 10
        idle = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"
    
[orm]
    dsn = "acc:123456@tcp(172.16.0.215:3306)/bilibili?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"


