[midMapping]
"1234"=1

[mysql]
	addr = "172.22.34.101:3306"
	dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_reply?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	active = 20
	idle = 2
	idleTimeout ="4h"
	queryTimeout = "500ms"
	execTimeout = "500ms"
	tranTimeout = "500ms"
	[mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[log]
stdout=true

[redis]
	name = "reply-feed-service"
	proto = "tcp"
	addr = "172.18.33.60:6889"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "1m"

[redisExpire]
    redisReplyZSetExpire = "12h"

[memcache]
	name = "reply-feed-service"
	proto = "tcp"
	addr = "172.18.33.61:11213"
	active = 50
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[databus]
    [databus.event]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "ReplyFeed-MainCommunity-P"
    topic = "ReplyFeed-T"
    action ="pub"
    name = "reply-feed/event"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 2
    active = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "1h"
