# This is a TOML document. Boom

version = "1.0.0"
user = "nobody"
pid = "/tmp/coupon.pid"
dir = "./"

[log]
# dir = "/data/log/coupon"
stdout = true

[tracer]
proto = "udp"
addr = "172.16.33.46:5140"
tag = "mypro"

[bm]
	addr = "0.0.0.0:9001"
	maxListen = 10
	timeout = "1s"

[mysql]
	addr = "127.0.0.1:3306"
	dsn = "root:123456@tcp(127.0.0.1:3306)/bilibili_coupon?timeout=3s&readTimeout=3s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "1s"
	execTimeout = "1s"
	tranTimeout = "2s"
	[mysql.breaker]
	window = "3s"
	sleep = "100ms"
	bucket = 10
	ratio = 0.5
	request = 100

[memcache]
	name = "coupon"
	proto = "tcp"
	addr = ""
	idle = 5
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
	expire = "24h"

[properties]
	maxRetries = 30
	bangumiNotifyURL = "http://bangumi.bilibili.com/pay/inner/notify_ticket"
	checkInUseCouponCron = "0 * */1 * * ?"
	CheckInUseCouponCartoonCron = "0 * */1 * * ?"
	notifyTimeInterval = "5s"

[httpClient]
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    key = "zxnh4k92dwe61t27"
    secret = "dnu3bwpxyswqwf1ixpsczthury1nqiew"
    [httpClient.breaker]
        window  = "3s"
        sleep   = "500ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
        switchoff = false  

[dataBus]
  [dataBus.couponBinlog]
    key = "4ba46ba31f9a44ef"
    secret = "e4c5a7fce28695209e6b4f0af8cf91c5"
    group = "CouponBinlog-MainAccount-S"
    topic = "CouponBinlog-T"
    action = "sub"
    offset = "old"
    buffer = 1024
    name = "vip-job"
    proto = "tcp"
    addr = "172.16.33.158:6205"
    idle = 1
    active = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
[newYearConf]
	# 活动id
	actID = 1