# This is a TOML document. Boom.

version = "3.0.0"
user = "nobody"
dir = "./"
perf = "0.0.0.0:6204"

addr = "0.0.0.0:6205"

[clusters]
[clusters.test_kafka_9092-266]
cluster = "test_kafka_9092-266"
brokers = ["127.0.0.1:9092"]
sync = false

[log]
dir = "/data/log/databus"

[httpServer]
addr = "0.0.0.0:6206"
timeout = "1s"

[mysql]
addr = "172.16.33.54:3306"
dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_databus_v2?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 2
idle = 1
idleTimeout ="4h"
queryTimeout = "150ms"
execTimeout = "100ms"
tranTimeout = "200ms"
[mysql.breaker]
window = "3s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100
