env       = "test"

[xlog]
dir = "/data/log/feedback/"

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[bm]
    [bm.outer]
    addr = "0.0.0.0:6171"
    timeout = "1s"
    [bm.local]
    addr = "0.0.0.0:6172"
    timeout = "1s"
         
[mysql]
    [mysql.master]
    addr   = "172.16.33.205:3308"
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_feedback?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    active = 5
    idle   = 2
    idleTimeout ="4h"
    queryTimeout = "100ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.master.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[bfs]
addr        = "http://bfs.bilibili.co"
bucket      = "test"
key         = "221bce6492eba70f"
secret      = "6eb80603e85842542f9736eb13b7e3"
# 上传文件大小限制为1M
maxFileSize = 1048576

[feedback]
# replys page size
replysNum = 50
# 发送内容长度限制为400字符
maxContentSize = 400
imgLimit = 4