#  toml config
version = "1.0.0"
user = "nobody"
pid= "/tmp/kvo.pid"
perf = "127.0.0.1:6690"
checkFile = "/data/www/kvo.html"
dir = "./"
family = "kvo"
address = ""

env  = "test"
docLimit = 102400

[mysql]
addr   = "172.16.33.54:3306"
dsn    = "test:test@tcp(172.16.33.54:3306)/bilibili_kvo?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle   = 2
    
[xlog]
dir = "/data/log/kvo/"
    # [xlog.elk]
    # project = "kvo"
    # addr = "172.18.20.17:8520"
    # chanSize = 10240

[tracer]
proto = "udp"
addr  = "172.16.33.46:5140"
tag   = "platform/kvo"

[multiHttp]
    [multiHttp.outer]
    addrs     = ["0.0.0.0:6691"]
    maxListen = 100
    [multiHttp.local]
    addrs     = ["0.0.0.0:6692"]
    maxListen = 100

[identify]
    whiteAccessKey = ""
    whiteMid = 0
    [identify.app]
    key = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.authHTTPClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
     [identify.secretHTTPClient.breaker]
    window  ="10s"
    sleep   ="10ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[memcache]
expire = "720h"
    [memcache.kvo]
    name = "kvo"
    proto = "tcp"
    addr = "172.16.33.54:11213"
    idle = 5
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
