[log]
    stdout = true
	
[mysql]
	addr = "172.16.33.205:3306"
	dsn = "upcrm:DdL6c5JaWCYKMAQ10PURbfeImow9HXlx@tcp(172.16.33.205:3306)/bilibili_upcrm?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	active = 5
	idle = 1
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
[mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[memcache]
	name = "mcn-admin"
	proto = "tcp"
	addr = "172.18.33.60:11216"
	active = 10
	idle = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"

[property]
    upMcnSignStateCron = "0 0 0 * * ?"
    upMcnUpStateCron = "0 0 0 * * ?"
	upExpirePayCron = "0 0 0 * * ?"
	upMcnDataSummaryCron = "0 5 0 * * ?"
    mcnRecommendCron     = "@hourly"
    dealFailRecommendCron = "@hourly"
	checkMcnSignUpDueCron = "0 20 0 * * ?"

[MailConf]
    host = "smtp.exmail.qq.com"
    port = 465
    username = "manager@bilibili.com"
    password = "123"
    DueMailReceivers = [""] # 需要发送的额外管理员名称
	DueAuthorityGroups = ["mcnplan@bilibili.com"]

[GRPCClient]
    [GRPCClient.account]
        timeout = "1s"
