version = "1.0.0"
user = "nobody"
dir = "./"
family = "esports-admin"
trace = false
debug = false
env = "qa"

[log]
dir = "/data/log/esports-admin/"

[orm]
dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_esports?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 5
idleTimeout = "4h"

[permit]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://uat-dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [permit.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [permit.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [permit.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [permit.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [permit.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[rule]
    maxCSVRows = 1000
    maxBatchArcLimit = 10
    maxTreeContests = 32

[httpReply]
    key = "96923574ed650ef9"
    secret = "35113863f243e6a84b8bbdafa2ba76cd"
    dial = "3s"
    timeout = "10s"
    keepAlive = "60s"

[[gameTypes]]
   id = 1
   name= "LOL"
[[gameTypes]]
   id = 2
   name= "DOTA2"